src/strategies/erc721-multi-registry/README.md
src/strategies/erc721-multi-registry/examples.json
src/strategies/erc721-multi-registry/index.ts
src/strategies/index.ts

This adds a strategy that allows to check addresses balance on multiple ERC721 tokens registry
- 
- 
-

[erc721-multi-registry] add multiple ERC721 registry strategy

---

src/strategies/delegation/index.ts

Here  if there is no address in the last strategy score (of delgation)  `x + y[b] || 0` it replaces the score with `0` which is making score of many addresses `0`
```
- (a, b) => a + scores.reduce((x, y) => x + y[b] || 0, 0),
+ (a, b) => a + scores.reduce((x, y) => y[b] ? (x + y[b]) : (x + 0), 0),
```

[delegation] Fix delegation strategy score calculation issue

---

src/strategies/multichain/examples.json

When you use the snapshot frontend, the parsing won't allow this strategy's params to be saved without the "symbol" property.
- add "symbol" property to multichain strategy example params.

[multichain] fix params in multichain strategy example to include token name

---

src/strategies/balancer-erc20-internal-balance-of/README.md
src/strategies/balancer-erc20-internal-balance-of/examples.json
src/strategies/balancer-erc20-internal-balance-of/index.ts
src/strategies/index.ts

- Adds a new strategy to query Internal User Balances in the Balancer V2 Vault for ERC20 tokens

[balancer-erc20-internal-balance-of] add vault internal balances strategy

---

src/strategies/infinityprotocol-liquidity-pools/README.md
src/strategies/infinityprotocol-liquidity-pools/examples.json
src/strategies/infinityprotocol-liquidity-pools/index.ts

Fixes # .
- edited infinityprotocol-liquidity-pools strategy so that any custom subGraphURL can be used
- Any project with Uniswap style subGraph can use this strategy to check balance of tokens in liquidity pools
- Added a scoreMultiplier so in case projects want to increase the scores of their liquidity providers

[infinityprotocol-liquidity-pools] changes in infinityprotocol-liquidity-pools strategy

---

src/strategies/cake/index.ts

- Update PancakeSwap subgraph URI to use TheGraph Hosted service.
Thanks as always!
> Note: This PR originate from the `pancakeswap` GitHub organisation, in order to verify its authenticity.

[cake]: Fix subgraph URI

---

src/strategies/flexa-capacity-staking/examples.json
src/strategies/flexa-capacity-staking/index.ts
src/strategies/index.ts

Allows for Amp stake + reward balances held within Flexa Capacity to be reflected in voting power

[flexa-capacity-staking] Add Flexa Capacity staking strategy

---

src/strategies/mcb-balance-from-graph/index.ts

Fixes the graph query failed caused by mixed-cases addresses.

[mcb-balance-from-graph] Fix graph query failed caused by mixed-cases address

---

src/strategies/the-graph-balance/README.md
src/strategies/the-graph-balance/balances.ts
src/strategies/the-graph-balance/examples.json
src/strategies/the-graph-balance/index.ts
src/strategies/the-graph-delegation/README.md
src/strategies/the-graph-delegation/delegators.ts
src/strategies/the-graph-delegation/examples.json
src/strategies/the-graph-delegation/index.ts
src/strategies/the-graph-indexing/README.md
src/strategies/the-graph-indexing/examples.json
src/strategies/the-graph-indexing/index.ts
src/strategies/the-graph-indexing/indexers.ts
src/strategies/the-graph/README.md
src/strategies/the-graph/baseStrategy.ts
src/strategies/the-graph/graphUtils.ts
src/strategies/the-graph/tokenLockWallets.ts

- Add pagination to `the-graph-*` strategies (by default 1000 addresses per subgraph request). Configurable through `pageSize` config param.
- Add documentation to strategies
- Modify `the-graph-balance` strategy to take Curator's signalled GRT as part of their balance
- Don't run scoring tests if snapshot === 'latest'

[the-graph-indexing] The Graph strategies refactor and documentation

---

src/strategies/the-graph-balance/balances.ts
src/strategies/the-graph-balance/index.ts
src/strategies/the-graph-delegation/delegators.ts
src/strategies/the-graph-delegation/index.ts
src/strategies/the-graph-indexing/index.ts
src/strategies/the-graph-indexing/indexers.ts
src/strategies/the-graph/baseStrategy.ts
src/strategies/the-graph/tokenLockWallets.ts

- Remove the `skip` param from The Graph strategies. It's not necessary as we already split the addresses into chunks and batch the requests. It is causing a bug where we don't fetch results for more than 1000 addresses.

[the-graph-balance] fix: The Graph strategies pagination

---

src/strategies/balancer/index.ts

- Adds support for pulling data from the Polygon/Arbitrum Balancer subgraphs.
The strategy will automatically skip attempting to query V1 on networks where it isn't deployed

[balancer] Add support for tracking tokens in Balancer pools on Polygon + Arbitrum

---

src/strategies/multichain/index.ts

- Adds a [default subgraph](https://thegraph.com/hosted-service/subgraph/ianlapham/arbitrum-one-blocks) for getting blocks on Arbitrum One

[multichain] feat: add arbitrum support to multichain strategy

---

src/strategies/multichain/examples.json
src/strategies/multichain/index.ts

This PR adds an optional startBlocks field to the multichain strategy. This avoids a space's historical vote counts changing in the situation where they add support for a new network.

[multichain] add optional start block for each network

---

src/strategies/tech-quadratic-ranked-choice/index.ts

After doing the square root of the balance, I forgot to reduce by half the amount of decimals at the formatUnits function.

[tech-quadratic-ranked-choice] Fix wrong decimal number on return

---

.github/workflows/strategy.yml

This should prevent strategy test workflow from failing when there are special characters in the PR title.

Handle special characters in pr title in strategy test workflow

---

src/strategies/api-post/README.md
src/strategies/api-post/examples.json
src/strategies/api-post/index.ts
src/strategies/api/examples.json
src/strategies/index.ts

New strategy "api-post"
- implements new strategy "api-post"
- addresses are sent via POST-Body to the given API
- fixed test for strategy "api"

[api-post] add api-post strategy

---

src/strategies/erc1155-with-multiplier/examples.json
src/strategies/erc1155-with-multiplier/index.ts
src/strategies/index.ts
test/index.spec.ts

Fixes #175 .
- new strategy: erc1155-with-multiplier
- comparable to erc721-with-multiplier
- allows to pass arbitrary multiplier that is applied to voting rights per token

Strategy: erc1155 with multiplier [erc1155-with-multiplier]

---

src/strategies/index.ts
src/strategies/math/README.md
src/strategies/math/examples.json
src/strategies/math/index.ts

This PR adds a new strategy `math` that allows composition of different strategies, similar to `multichain`.
As an example use case, a project might want to use user ERC20 token balances as voting socre, but to also limit whales by applying a square root operation on the balances. Instead of submitting yet another `project-x-strategy` to this repository, they can just pipe `erc20-balance-of` into `math` instead, keeping the strategy directory clean and reducing (mostly) duplicate code.

[math] Add math strategy

---

src/strategies/index.ts
src/strategies/whitelist-weighted/README.md
src/strategies/whitelist-weighted/examples.json
src/strategies/whitelist-weighted/index.ts

This strategy returns weighted votes for addresses matching a static whitelist.
It's derived from the existing `whitelist` strategy.
```
$ npm run test --strategy=whitelist-weighted --more=200
> @snapshot-labs/strategies@0.1.0 pretest
> npm run build
> @snapshot-labs/strategies@0.1.0 build
> tsc -p .
> @snapshot-labs/strategies@0.1.0 postbuild
> copyfiles -u 1 src/**/*.md dist/ && copyfiles -u 1 src/**/*.json dist/
> @snapshot-labs/strategies@0.1.0 test
> jest test/index.spec.ts --runInBand --testTimeout=120000
console.log
[
{
'0xa478c2975ab1ea89e8196811f51a7b7ade33eb11': 5,
'0xeF8305E140ac520225DAf050e2f71d5fBcC543e7': 2,
'0x1E1A51E25f2816335cA436D65e9Af7694BE232ad': 0
}
]
at Object.<anonymous> (test/index.spec.ts:47:13)
console.log
Resolved in 0.00 sec.
at Object.<anonymous> …
```

[whitelist-weighted] Add whitelist-weighted strategy

---

src/strategies/index.ts
src/strategies/snet-liquidity-providers/README.md
src/strategies/snet-liquidity-providers/examples.json
src/strategies/snet-liquidity-providers/index.ts

This strategy returns the liquidity pool balances of the voters for the SingularityNET project.

[snet-liquidity-providers] strategy: snet-liquidity-providers

---

src/strategies/math/README.md
src/strategies/math/examples.json
src/strategies/math/index.ts
src/strategies/math/options.ts

This PR:
- changes `math` params structure to support multi-operand operations, while maintaining backward compatibility by automatically converting the old format to the new one; and
- adds two new operations: `min` and `max`; and
- bumps `math` version to `0.2.0`.
Operations like `min` and `max` are useful in cases where DAOs want to limit any single account's voting power, or to set a minimum threshold. All they have to do is to nest their original strategies into `math` as a `strategy` operand, and apply a `min`/`max` operation against a constant operand.
The original example is left untouched to demonstrate backward compatibility, and 2 new examples have been added to demonstrate the new `options` format and `math` strategy nesting.

[math] Add min and max operations to `math` strategy

---

src/strategies/glide/examples.json
src/strategies/glide/index.ts
src/strategies/index.ts

This is a custom strategy for Glide Finance, an AMM/DEX on the Elastos Smart Chain (ESC).
The strategy returns the total amount of user-owned GLIDE tokens for use as voting power, including GLIDE held in wallet, staked, and in various LPs.

[glide] Add custom strategy for Glide Finance

---

src/strategies/erc721-with-tokenid-weighted/README.md
src/strategies/erc721-with-tokenid-weighted/examples.json
src/strategies/erc721-with-tokenid-weighted/index.ts
src/strategies/index.ts

This strategy is a modification of erc721-with-tokenid by dimsome. Instead of a maximum one vote per wallet, this strategy allows for multiple votes from a single wallet. For example, a wallet containing three whitelisted ERC721 TokenIDs would receive three votes.
In short, this strategy provides one vote per whitelisted ERC721 TokenID- regardless of wallet distribution.

[erc721-with-tokenid-weighted] Create erc721-with-tokenid-weighted Strategy

---

src/strategies/math/README.md
src/strategies/math/examples.json
src/strategies/math/index.ts
src/strategies/math/options.ts

This PR:
- adds 4 new operations:
- `a-if-lt-b`
- `a-if-lte-b`
- `a-if-gt-b`
- `a-if-gte-b`
- bumps `math` version to `0.2.1`.

[math] Add 4 new operations to `math` strategy

---

src/strategies/multichain/README.md
src/strategies/multichain/index.ts

The existing multichain strategy requires a working subgraph on every chain that wants to be included. Some chains, such as HECO, CRONOS or HARMONY are not supported at the moment by the subgraph hosted service and are therefor unable to be added and used. As a solution to this, I propose adding an external API source as an option to use in place of subgraphs for block number fetching.
If the strategy's options contains the 'blockApi' property, it will be used as a base url from where to fetch block height numbers. This allows developers to create their own custom APIs that, given a timestamp, return the block height for every chain they support, no matter if there is a subgraph for that chain or not. **A single API call** should be done to fetch all …

[multichain] Support multichain strategy block fetching from custom API

---

src/strategies/erc20-balance-of-indexed/README.md
src/strategies/erc20-balance-of-indexed/examples.json
src/strategies/erc20-balance-of-indexed/index.ts
src/strategies/index.ts

Fixes #281 
- Add a strategy to multiply token balances by an ever-increasing index value.

[erc20-balance-of-indexed] Add erc20-balance-of-indexed strategy

---

src/strategies/digitalax-deco-to-mona/README.md
src/strategies/digitalax-deco-to-mona/examples.json
src/strategies/digitalax-deco-to-mona/index.ts
src/strategies/index.ts

This is a new strategy for Digitalax
What it does is queries your balance of our DECO token
Converts to ETH value
Converts to MONA value
For our MONA based snapshot voting
Uses a certain subgraph for quickswap to get the pair conversion prices
Cheers

[digitalax-deco-to-mona] new strategy

---

src/strategies/sushiswap/README.md
src/strategies/sushiswap/examples.json
src/strategies/sushiswap/index.ts

- Add masterchef v2 handling to staked LP power by adding a key `options.masterchefVersion` which defaults to v1 for backward compatibility but can be set to v2 for newer LP staked in the v2 masterchef contract.

[sushiswap] Add masterchef v2 stakedLP + all sushi chains

---

src/strategies/immutable-x/index.ts

- Replace Immutable X strategy logic for adding query param `block` because test environment shows error when a string is used

Use typeof for latest block query param in snapshot strategy [immutable-x]

---

src/strategies/defiplaza/README.md
src/strategies/defiplaza/examples.json
src/strategies/defiplaza/index.ts
src/strategies/defiplaza/schema.json
src/strategies/index.ts

This new strategy looks at `balanceOf` and the `quoteRewards` function of the DFP2 governance contract to be able to use the balance of unclaimed staking rewards in the voting process, next to the balance of DFP2 in a wallet.
The addresses in the `examples.json` are the current biggest DFP2 holders to create a real-world test scenario.
* Add new DefiPlaza strategy
Here is the simple checklist to look when reviewing a PR for a new strategy:
* ✅ The strategy must be unique.
* ✅ If the strategy does only a single call with an address as input, it's preferable to use the strategy "contract-call" instead of creating a new one.
* ✅ There should be a maximum of 5 requests, a request can use "fetch" a "subgraphRequest" or "multicall".
* ✅ The strategy should …

[defiplaza] feat: new DefiPlaza strategy

---

src/strategies/printer-financial/examples.json
src/strategies/printer-financial/index.ts
src/strategies/printer-financial/schema.json

Adds lpPoolId to the configurable settings in the printer-financial strategy

[printer-financial] add pool id to printer-financial strategy

---

src/strategies/index.ts
src/strategies/safety-module-bpt-power/README.md
src/strategies/safety-module-bpt-power/examples.json
src/strategies/safety-module-bpt-power/index.ts
src/strategies/safety-module-bpt-power/schema.json

- new strategy to support bpt powered aave-live safety module (sktAbpt, stkPSPBpt, etc...)
Easiest way to test: compare what script returns vs https://debank.com/profile/0x0ddc793680ff4f5793849c8c6992be1695cbe72a (go to ParaSwap farming section and record amount of PSP locked + PSP rewards)

[safety-module-bpt-power] Add safety module bpt strategy

---

src/strategies/index.ts
src/strategies/protofi-erc721-tier-weighted/README.md
src/strategies/protofi-erc721-tier-weighted/examples.json
src/strategies/protofi-erc721-tier-weighted/index.ts

- Adds a new strategy to take voting power from ProtoNFT holders
- Assign voting power using a weight based on the tier of the NFT
- If the NFT is "used", you can use the parameter countUsed to determine if the used NFT has voting power or not

[protofi-erc721-tier-weighted] Protofi nft strategy

---

src/strategies/ocean-marketplace/index.ts

Updating ocean subgraph routes for BSC & Poly network.
- Enables us to expand marketplace strategy support for BSC & Poly

[ocean-marketplace] Add other networks for ocean-marketplace strategy

---

src/strategies/swapr/commons.ts

Updates the Swapr Arbitrum One subgraph endpoint to the most recent one.

[swapr] fix: update Swapr Arbitrum One subgraph endpoint

---

src/utils/delegation.ts

Returning empty object in case of node delegations in the page

Fix delegation empty response in pagination

---

src/strategies/erc20-votes-with-override/README.md
src/strategies/erc20-votes-with-override/index.ts

The standard "delegation" strategy is not compatible with the overridden voting power calculation, because it can lead to double-counting.
So instead, this strategy adds an "includeSnapshotDelegations" option. When enabled, one additional request is made to the subgraph to get Snapshot delegations. Then the unique delegators are added to the list of addresses and the normal overridden voting power calculation is used as before.
The "isSnapshotDelegatedScore" option determines whether the delegated or non-delegated score is used. So two strategies can be used, one with this option enabled and one with this option disabled.
#449

[erc20-votes-with-override] Adding compatibility for Snapshot delegations.

---

src/strategies/meebitsdao-delegation/index.ts

-Update strategy to add miniumum multiplier 1 for meebitsScore (instead of just # meebits, up to 20 but minimum prev. 0).
-Update score to give max capped 1000 voting power to any given individual.
Created this strategy a few days ago, just was told we had to slightly update our multiplier in the formula. Very small change.

[meebitsdao-delegation] small update/fix: Update strategy to add miniumum multiplier 1

---

src/strategies/reverse-voting-escrow/examples.json
src/strategies/reverse-voting-escrow/index.ts

This PR fixes the `reverse-voting-escrow` BigNumber conversion for scores to use a decimal option for the strategy input.

[reverse-voting-escrow] Fixes Reverse Voting Escrow Scores

---

src/strategies/index.ts
src/strategies/samurailegends-generals-balance/README.md
src/strategies/samurailegends-generals-balance/examples.json
src/strategies/samurailegends-generals-balance/index.ts

This commits adds the Samurai Legends Generals voting strategy. The voting power is determined by how many generals a user has. Calculated from a batch nft contract.

[samurailegends-generals-balance] add generals balance test for samurai legends

---

src/strategies/cake/index.ts

- handle case when specify block number is not indexed on subgraph

[cake] handle subgraph error when block number not sync

---

src/strategies/erc721-with-tokenid-range-weights-simple/README.md
src/strategies/erc721-with-tokenid-range-weights-simple/examples.json
src/strategies/erc721-with-tokenid-range-weights-simple/index.ts
src/strategies/erc721-with-tokenid-range-weights-simple/types.d.ts

-  Improves performance for the `erc721-with-tokenid-range-weights-simple` strategy, reducing external calls, and allowing more than 5 ranges to be used.
-  Add's an optional `defaultWeight` parameter to `erc721-with-tokenid-range-weights-simple` strategy

[erc721-with-tokenid-range-weights-simple] Erc721 with tokenid range weights simple v2

---

src/strategies/index.ts
src/strategies/liquidity-token-provide/README.md
src/strategies/liquidity-token-provide/examples.json
src/strategies/liquidity-token-provide/index.ts

infinityprotocol-liquidity-pools has some tech issue that can't support quickswap's subgraph query and I update the subgraph query it also compatible with uniswap fork's subgraph.
- replace  infinityprotocol-liquidity-pools subgraph query with liquidtyPositions

feat: update infinityprotocol-liquidity-pools subgraph query [liquidity-token-provide]

---

src/strategies/citydao-square-root/README.md
src/strategies/citydao-square-root/examples.json
src/strategies/citydao-square-root/index.ts
src/strategies/erc1155-balance-of/examples.json
src/strategies/index.ts

This PR adds CityDAO's Square Root Strategy.  More info can be found in its [README](https://github.com/721labs/snapshot-strategies/blob/citydao-square-root/src/strategies/citydao-square-root/README.md).
- Strategy `citydao-square-root@0.0.1`
- None

Adds: citydao-square-root 0.0.1 [citydao-square-root]

---

src/strategies/erc721-with-tokenid-range-weights-simple/README.md
src/strategies/erc721-with-tokenid-range-weights-simple/examples.json
src/strategies/erc721-with-tokenid-range-weights-simple/index.ts
src/strategies/erc721-with-tokenid-range-weights-simple/types.d.ts

- Improves performance for the erc721-with-tokenid-range-weights-simple strategy, reducing external calls, and allowing more than 5 ranges to be used.
- Add's an optional defaultWeight parameter to erc721-with-tokenid-range-weights-simple strategy
- Add a limit of 32,000 tokenIDs as discussed on [discord](https://discord.com/channels/707079246388133940/747050056422785055/971858296984182824) and [here](https://github.com/snapshot-labs/snapshot-score/pull/330)

Erc721 with tokenid range weights simple v2 with fix [erc721-with-tokenid-range-weights-simple]

---

src/strategies/index.ts
src/strategies/recusal-list/README.md
src/strategies/recusal-list/examples.json
src/strategies/recusal-list/index.ts
src/strategies/recusal-list/schema.json

Fixes # . n/a
- Adds Recusal List strategy. This is strategy for disallowing certain address from voting due to conflict of interest or other reasons for recusal.

Add recusal list strategy [recusal-list]

---

src/strategies/genzees-from-subgraph/README.md
src/strategies/genzees-from-subgraph/examples.json
src/strategies/genzees-from-subgraph/index.ts
src/strategies/index.ts

This adds `genzee-from-subgraph` for Oddworx DAO, it grabs the `genzeeBalance` from the subgraph. Couldn't use the regular erc721 strategies because we have staking, which changes the token ownership in the contract. The subgraph takes staking into consideration.

add genzees-from-subgraph strategy [genzees-from-subgraph]

---

src/strategies/ens-10k-club/README.md
src/strategies/ens-10k-club/examples.json
src/strategies/ens-10k-club/index.ts
src/strategies/index.ts

This strategy is for 10K Club members, holders of ENS names 000.eth - 9999.eth. This script queries The Graph for all ENS names owned by voter and checks for 10K Club names. By default, 999 Club members' votes are weighted 10x.

Add strategy for ENS 10k Club [ens-10k-club]

---

src/strategies/arrakis-finance/schema.json

- Fix bug in `arrakis-finance` schema where `poolAddress` displayed the title "Token address" and was indistinguishable from the actual `tokenAddress` param.
- Update all the titles in the `arrakis-finance` schema to exactly match the param name - for better snapshot playground UX.
Screenshots:

fix schema [arrakis-finance] 

---

src/strategies/aura-vlaura-vebal/README.md
src/strategies/aura-vlaura-vebal/examples.json
src/strategies/aura-vlaura-vebal/index.ts
src/strategies/aura-vlaura-vebal/schema.json
src/strategies/index.ts

This strategy returns proportional voting power for vlAURA holders based on system owned veBAL.
For example:
- there are 10000 vlAURA total supply
- a user has 2000 vlAURA (voting power, delegated to them)
- Aura's voterProxy owns 100k veBAL
In this example, the user has 20k veBAL voting power as they own 20% of the vlAURA voting power.
_Note: When depositing to the auraLocker, a user does not receive vlAURA until the next epoch has begun (Thursday at 00:00 UTC)_

Add vlAURA voting strategy for Balancer [aura-vlaura-vebal]

---

src/strategies/balance-of-with-linear-vesting-power/examples.json
src/strategies/balance-of-with-linear-vesting-power/index.ts
src/strategies/index.ts

Morpho’s voting strategy is the `balanceOf()` strategy with a slight twist enabling locked/vested holders to benefit from their voting power, proportionally to the time tokens have been locked/vested.

:sparkles: add balance of and vesting power strategy [balance-of-with-linear-vesting-power]

---

src/strategies/index.ts
src/strategies/rari-fuse/README.md
src/strategies/rari-fuse/examples.json
src/strategies/rari-fuse/index.ts
src/strategies/rari-fuse/schema.json

- Add a `rari-fuse` strategy that returns the voter's underlying collateral balances in a given Rari Fuse market (fToken).

Add rari-fuse strategy [rari-fuse]

---

src/strategies/defiplaza/README.md
src/strategies/defiplaza/examples.json
src/strategies/defiplaza/index.ts
src/strategies/defiplaza/schema.json

Fixes # .
- update `defiplaza` strategy to include the DFP2 tokens staked in the new StablePlaza pool contract. By not making this a mandatory option, the strategy is backward compatible.

feat(defiplaza): update defiplaza strategy to include StablePlaza pool [defiplaza]

---

src/strategies/aura-vlaura-vebal-with-overrides/README.md
src/strategies/aura-vlaura-vebal-with-overrides/examples.json
src/strategies/aura-vlaura-vebal-with-overrides/index.ts
src/strategies/aura-vlaura-vebal-with-overrides/schema.json
src/strategies/index.ts

- Provide optional delegation overrides for a new `aura-vlaura-vebal-with-overrides` strategy based on delegated vlAURA
- Reuse the `erc20-votes-with-override` strategy and rescale scores to get proportional shares of Aura's underlying veBAL; i.e. the same scoring system as `aura-vlaura-vebal` currently uses, but with optional delegation overrides

feat: Add Aura vlAURA delegation [aura-vlaura-vebal-with-overrides]

---

src/strategies/delegation/index.ts
src/strategies/echelon-cached-erc1155-decay/README.md
src/strategies/echelon-cached-erc1155-decay/examples.json
src/strategies/echelon-cached-erc1155-decay/index.ts
src/strategies/index.ts

Adding new voting strategy for https://echelon.io/.
Explanation of logic:
- each cached ERC 1155 has a decaying amount of voting power
- at the starting block time, each asset has 4000 units of voting power, one year later it should be 0; this value decays linearly per second
- once we assign the corresponding votes for each address, we square the final value

new strategy: decaying voting power for staked ERC 1155s [echelon-cached-erc1155-decay]

---

src/strategies/harmony-staking/examples.json
src/strategies/harmony-staking/index.ts
src/strategies/index.ts

calculates votes of validators through the total balance delegated to
them (including self delegation)
- add harmony staked balance strategy for validator addresses

feat: add harmony-staking strategy [harmony-staking]

---

src/strategies/balance-of-subgraph/README.md
src/strategies/balance-of-subgraph/examples.json
src/strategies/balance-of-subgraph/index.ts
src/strategies/index.ts

To calculate the token balance including user’s EOA and smart wallet, we developed this strategy. Developers can create their own subparagraphs.
- new balance of strategy with the subgraph data source

feat: add a strategy to calc blance with subgraph [balance-of-subgraph]

---

src/strategies/aura-balance-of-vlaura-vebal/README.md
src/strategies/aura-balance-of-vlaura-vebal/examples.json
src/strategies/aura-balance-of-vlaura-vebal/index.ts
src/strategies/aura-balance-of-vlaura-vebal/schema.json
src/strategies/aura-vlaura-vebal/README.md
src/strategies/index.ts

This PR adds a new strategy, `aura-balance-of-vlaura-vebal`. This strategy is similar to the existing `aura-vlaura-vebal` strategy, in that it represents the underlying veBAL of vlAURA holdings, but instead of using the delegated voting power (i.e. `AuraLocker.getVotes`), it uses a simple `balanceOf` call.

feat: Add vlAURA to veBAL balanceOf strategy [aura-balance-of-vlaura-vebal]

---

src/strategies/index.ts
src/strategies/proxyprotocol-erc1155-balance-of/README.md
src/strategies/proxyprotocol-erc1155-balance-of/examples.json
src/strategies/proxyprotocol-erc1155-balance-of/index.ts

New strategy for ERC 1155 for using proxy wallet mappings to actual wallet mappings to calculate voting power.
**Example:**
wallet 0xABC is a proxy wallet that maps to [0x123, 0x456, 0x789]
I calculate the voting power from [0x123, 0x456, 0x789] as [0, 1, 4]
I sum the voting power from all the wallets as 5
wallet 0xABC has voting power of 5
> the service is a community management tool that allows communities to have social functionality on top of snapshot and other governance features like idea boards/ forums. https://app.proxychat.xyz/post/PN7bFYYikNqD58s74x5F/
> 
> we want to allow users to vote with a proxy wallets so that you don't need to sign using your cold wallet everytime you want to vote with your NFT.
> 
> the mapping returned here is a …

Proxy Protocol ERC1155 [proxyprotocol-erc1155-balance-of]

---

src/strategies/index.ts
src/strategies/proxyprotocol-erc721-balance-of/README.md
src/strategies/proxyprotocol-erc721-balance-of/examples.json
src/strategies/proxyprotocol-erc721-balance-of/index.ts
src/strategies/proxyprotocol-erc721-balance-of/schema.json

New strategy for ERC 721 for using proxy wallet mappings to actual wallet mappings to calculate voting power.
**Example:**
wallet 0xABC is a proxy wallet that maps to [0x123, 0x456, 0x789]
I calculate the voting power from [0x123, 0x456, 0x789] as [0, 1, 4]
I sum the voting power from all the wallets as 5
wallet 0xABC has voting power of 5
> the service is a community management tool that allows communities to have social functionality on top of snapshot and other governance features like idea boards/ forums. https://app.proxychat.xyz/post/PN7bFYYikNqD58s74x5F/
> 
> we want to allow users to vote with a proxy wallets so that you don't need to sign using your cold wallet everytime you want to vote with your NFT.
> 
> the mapping returned here is a …

Proxy Protocol ERC721 [proxyprotocol-erc721-balance-of]

---

src/strategies/arrow-vesting/README.md
src/strategies/arrow-vesting/examples.json
src/strategies/arrow-vesting/index.ts
src/strategies/index.ts

Fixes #na.
- Adds a new strategy that returns the sum of the locked balance in all vesting contracts from a factory that hold a particular address as a beneficiary.

Add vesting contract strategy [arrow-vesting]

---

src/strategies/gysr-pending-rewards/README.md
src/strategies/gysr-pending-rewards/examples.json
src/strategies/gysr-pending-rewards/index.ts
src/strategies/gysr-pending-rewards/schema.json
src/strategies/index.ts

This strategy returns the pending rewards for each user in a specified GYSR pool as the voting power. It supports the networks the GYSR Pool Info is available.

[gysr-pending-rewards] Add gysr-pending-rewards strategy

---

src/strategies/harmony-staking/examples.json

- allow strategy `harmony-staking` to be used on Harmony testnet (1666700000)

[harmony-staking] add testnet example

---

src/strategies/lrc-l2-nft-balance-of/README.md
src/strategies/lrc-l2-nft-balance-of/examples.json
src/strategies/lrc-l2-nft-balance-of/index.ts

adding options for blacklisting nft id's and filter by token id(s) instead of minter account id
- Improve filter of NFT's by add tokens as a parameter to be an alternative to minter account id
- Improve blacklisting by add blacklisted_nft_id's so mismints or any other nft can be excluded from the result set

Improvement and more options to LRC L2 NFT balance strategy [lrc-l2-nft-balance-of]

---

src/strategies/echelon-wallet-prime-and-cached-key/README.md
src/strategies/echelon-wallet-prime-and-cached-key/examples.json
src/strategies/echelon-wallet-prime-and-cached-key/index.ts
src/strategies/index.ts

Adding new voting strategy for https://echelon.io/.
Explanation of logic:
- each cached ERC 1155 has a decaying amount of voting power
- at the starting block time, each asset has 4000 units of voting power, one year later it should be 0; this value decays linearly per second
- use `erc20-balance-of` to grab erc20 tokens in value and add to calculated erc1155 value
- once we assign the corresponding votes for each address, we square the final value

new echelon voting strategy [echelon-wallet-prime-and-cached-key]

---

src/strategies/otterspace-badges/index.ts

If a badge is expired, weight would be set to 0.

otterspace-badges: Added logic for considering expiring badges in strategy [otterspace-badges]

---

src/strategies/index.ts
src/strategies/wagdie-subgraph/README.md
src/strategies/wagdie-subgraph/examples.json
src/strategies/wagdie-subgraph/index.ts

This is a modified version of `balance-of-subgraph` to track users WAGDIE balances via snapshot. 
Changes proposed:
* Add wagdie-subgraph strategy to compute votes using the `ownedWAGDIE` account value from the wagdieworld subgraph.

Add new strategy wagdie-subgraph [wagdie-subgraph]

---

src/strategies/bancor-standard-rewards-underlying-balance/examples.json
src/strategies/bancor-standard-rewards-underlying-balance/index.ts
src/strategies/index.ts

- Adding the `bancor-standard-rewards-underlying-balance` to get the underlying voting power of the LP tokens staked in the Bancor 3 external Standard Rewards contract.
The strategy:
1. Gets the latest Standard Rewards program for a token by getting latestProgramId for the underlyingToken.
2. Calculates the underlying value of the provider's LP tokens in that Standard Rewards Program.

Adding Bancor 3 Standard Rewards Strategy [bancor-standard-rewards-underlying-balance]

---

src/strategies/index.ts
src/strategies/ninechronicles-staked-and-dcc/README.md
src/strategies/ninechronicles-staked-and-dcc/examples.json
src/strategies/ninechronicles-staked-and-dcc/index.ts

This PR adds a new strategy using [Nine Chronicles]'s staked assets.
- Since Nine Chronicles has its own mainnet other than Ethereum or other evm-compact chains, it needs some GrpahQL requests, and a block hash as a parameter to specify the point of snapshot time on that chain. [^1]
- I'm pretty new to snapshot strategies. so, there may be wrong codes or additional corrections to be made. please let me know.
[Nine Chronicles]: https://nine-chronicles.com/
[^1]: I also think it's a little bit weird and I might revise this version with a snapshot mapper in near future. :sweat_smile:

Introduce ninechronicles-staked-and-dcc [ninechronicles-staked-and-dcc]

---

src/strategies/staked-balancer/index.ts

Fixes not working staked-balancer strategy. Root cause for the issue is in logic responsible for making calls to Balancer subgraph, where it tries to query address field on Pool entity, which is present in subgraph of Balancer V2, but not in subgraph for Balancer V1. However, querying address field can be removed, as it's not being used inside strategy. 
- remove querying address field of Pool entity in Subgraph api call.

Staked-Balancer: remove unused variable in subgraph call [staked-balancer]

---

src/strategies/safe-vested/README.md
src/strategies/safe-vested/examples.json
src/strategies/safe-vested/index.ts

Update to `safe-vested` strategy to consider a claim date limit in the vesting contracts.
- Add a new parameter `claimDateLimit` that allows configuring a date limit when the vesting is allowed

Add claimDateLimit parameter to safe-vested strategy [safe-vested]

---

src/strategies/decentraland-estate-size/index.ts
src/strategies/decentraland-wearable-rarity/index.ts

- `decentraland-wearable-rarity` and `decentarland-estate-size` now query addresses in batches of 500. As 500 is the limit of addresses to query in both subgraphs.

[decentraland-wearable-rarity] fix: decentraland strategies with too many addresses

---

src/strategies/index.ts
src/strategies/metropolis-pod/README.md
src/strategies/metropolis-pod/examples.json
src/strategies/metropolis-pod/index.ts
src/strategies/metropolis-pod/schema.json

This adds a new Metropolis Pod strategy intended to replace the Orca Pod strategy, as we have rebranded to Metropolis. 
We should make sure the Orca Pod strategy does not display in UI to not confuse users.
Have confirmed tests are passing.

Add Metropolis Pod strategy [metropolis-pod]

---

src/strategies/ninechronicles-staked-and-dcc/README.md
src/strategies/ninechronicles-staked-and-dcc/examples.json
src/strategies/ninechronicles-staked-and-dcc/index.ts

This PR revises `ninechronicles-staked-and-dcc` strategy (introduced in #901), to use [Wrapped Nine Chronicles Gold(wNCG)][wNCG] instead of its LP token. (thanks @lounlee)
I'm still newer to snapshot strategies, so please let me know if there are any more fixes or things to consider when version bumping.
[wNCG]: https://etherscan.io/token/0xf203ca1769ca8e9e8fe1da9d147db68b6c919817

Revise ninechronicles-staked-and-dcc [ninechronicles-staked-and-dcc]

---

test/strategy.test.ts

`getVp` need returned address to be checksummed 
related to #958

Make sure returned addresses are checksum

---

src/strategies/index.ts
src/strategies/skale-delegation-weighted/README.md
src/strategies/skale-delegation-weighted/examples.json
src/strategies/skale-delegation-weighted/index.ts

Hi snapshot-labs team,
Please review and add my strategy.
SKALE foundation want to create a weighted vote system, to allow SKL token holders to vote.
Only delegated SKL tokens would be considered as a weight.
SKL tokens can be delegated from the EOA address/Gnosis Safe/other multisig solutions or through Escrow contracts.
Checking how many SKL tokens delegated from given address, then checks is there a Escrow linked to this address and checks how many SKL tokens delegated from Escrow.
skale-allocator repo(contains Escrow contract): https://github.com/skalenetwork/skale-allocator/tree/stable
skale-manager repo(contains delegation system): https://github.com/skalenetwork/skale-manager
Delegation docs: https://docs.skale.network/validators/delegation
Snapshot is incredible solution, and …

Add skale delegation weighted strategy [skale-delegation-weighted]

---

src/strategies/linear-vesting-power/index.ts

- update `linear-vesting-power` to handle multiple vesting lines for one address
- add explanation on the strategy to make it more understandabl

[linear-vesting-power] Handle multiple vesting lines

---

src/strategies/erc20-balance-of-at/README.md
src/strategies/erc20-balance-of-at/examples.json
src/strategies/erc20-balance-of-at/index.ts
src/strategies/erc20-balance-of-at/schema.json
src/strategies/index.ts

Add Strategy erc20-balance-of-at .
- Add a strategy that uses ERC20 Snapshot that will rely on an on-chain snapshot in the token contract
- Allows tokens that invoke a contact-level snapshot that returns actual balances along with staked token balances if the token contract implements this functionality to utilize snapshot.org

[erc20-balance-of-at] Add Strategy - erc20-balance-of-at

---

src/strategies/hashflow-vehft/README.md
src/strategies/hashflow-vehft/examples.json
src/strategies/hashflow-vehft/index.ts
src/strategies/hashflow-vehft/schema.json
src/strategies/index.ts

- Implements a new strategy 'hashflow-vehft' for the Hashflow DAO which translates locked HFT to voting power (veHFT-style governance)
- One intricacy is that the voting power gets multiplied by 110% for holders of the Creation's Coffer NFT
- This strategy was implemented as a result of the pre-launch of the Hashverse
Test Plan:
While tests seem to be flaky for all strategies (including the standard ERC20 strategy), I did get this to pass end-to-end once

Add Hashflow veHFT strategy. [hashflow-vehft]

---

src/strategies/index.ts
src/strategies/stakedotlink-vesting/README.md
src/strategies/stakedotlink-vesting/examples.json
src/strategies/stakedotlink-vesting/index.ts
src/strategies/stakedotlink-vesting/schema.json

- Added new strategy for stake.link vested stSDL tokens
- To calculate it uses their `totalBalanceOf - balanceOf`
- Vesting tokens need to be taken into account alongside other default strategies for voting weight

[stakedotlink-vesting] add strategy to calculate vesting tokens

---

src/strategies/api/README.md
src/strategies/api/examples.json
src/strategies/api/index.ts

- Remove the `symbol` and `decimal` parameters from `example.json`. This was probably copied from erc20 strategy but it's not used at all for the api strategy.
- Add a readme to explain how the api strategy is used.
Verified the api strategy passes all tests

Fix test for API strategy. Make `decimals` parameter optional and add Readme.

---

src/strategies/index.ts
src/strategies/lqty-proxy-stakers/README.md
src/strategies/lqty-proxy-stakers/examples.json
src/strategies/lqty-proxy-stakers/index.ts

Fixes # .
- Created a strategy for counting LQTY staked by a user via his DSProxy

[lqty-proxy-stakers] create lqty proxy staking strategy

---

src/strategies/moonbeam-free-balance/examples.json
src/strategies/moonbeam-free-balance/index.ts

Moonbeam free balance strategy is returning raw instead of formatted tokens value.
This PR fixes it

[moonbeam-free-balance] Format moonbeam strategy to include decimals

---

src/strategies/delegation-with-overrides/README.md
src/strategies/delegation-with-overrides/examples.json
src/strategies/delegation-with-overrides/index.ts
src/strategies/index.ts

- Adds a new strategy, `delegation-with-overrides`. The use-case for this strategy is to forward delegated votes to an address defined in the strategy, via an overrides mapping param.

[delegation-with-overrides] feat: Add delegation-with-overrides

---

src/strategies/ogn/README.md
src/strategies/ogn/examples.json
src/strategies/ogn/index.ts

We (Origin Protocol) recently moved from our old legacy staking to a new staking contract.  This updates the calls required for it, the addresses in `example.json`, and a minor verbiage change.
- Update `ogn` strategy to utilize new staking system, removing support for the old

[ogn] Update OGN strategy for new series staking

---

src/strategies/echelon-wallet-prime-and-cached-key-gated/README.md
src/strategies/echelon-wallet-prime-and-cached-key-gated/examples.json
src/strategies/echelon-wallet-prime-and-cached-key-gated/index.ts
src/strategies/index.ts

Echelon Foundation (echelon.io) has recently made our ERC20 token transferable, and as such, want to restrict the voting criteria on key votes. This strategy extends `echelon-wallet-prime-and-cached-key`. 
In order to have voting power, the address must hold a ERC1155 token in their wallet or be whitelisted. The address also cannot be blacklisted.
- new strategy that extends `echelon-wallet-prime-and-cached-key` with additional voting criteria

new strategy: Echelon voting strategy with eligibility criteria [echelon-wallet-prime-and-cached-key-gated]

---

src/strategies/aura-vault-balance-of-single-asset/README.md
src/strategies/aura-vault-balance-of-single-asset/examples.json
src/strategies/aura-vault-balance-of-single-asset/index.ts
src/strategies/index.ts

Fixes # .
- Gets underlying balance of aura vault deposit token. For example, if I own `aura50WETH-50AURA-vault` I want to get my share of underlying Balancer vault's Aura balance
- 
-

add aura vault deposit token underlying asset balance [aura-vault-balance-of-single-asset]

---

src/strategies/otterspace-badges/examples.json
src/strategies/otterspace-badges/index.ts

1. Adds 2 new neworks - Mainnet & Optimism goerli
2. Udpates logic for using the badge with the highest weight when an address holds multiple badges
3. Updates exmaples' address to using checksums

Otterspace - new networks [otterspace-badges]

---

README.md

This PR is reflecting the test requirements - making sure that strategies are using a snapshot to calculate user's voting power.

require strategies to use snapshot

---

src/strategies/math/index.ts

I wanted to be able to be able to multiple a token balance on mainnet with one on polygon but that wasn't possible even when `network` was explicitly provided to the `operand`s.

Multinetwork Support for Math [math]

---

src/strategies/math/README.md

Small wording fix
- The Readme says that "the following example takes the cube roots of [...]" but it is actually taking the square root

Updated `README.md` of the math strategy

---

src/utils/delegation.ts

We perform reversing the map and calling `getAddress` on lots of addresses when querying for VP which is slow synchronous code (60 ms per strategy, 8 strategies in case of Stargate).
Refactoring it to add 5 min cache for stgdao.eth only to test if it solves high CPU usage.

feat: cache stgdao delegates for 5 minutes [with-delegation]

---

src/strategies/skale-delegation-weighted/README.md
src/strategies/skale-delegation-weighted/examples.json
src/strategies/skale-delegation-weighted/index.ts

Hey Snapshot team!!
It is pleasure to contribute to your repo again!
So after my previous contribution https://github.com/snapshot-labs/snapshot-strategies/pull/966 , we decided to add more functionality to the strategy, so now not only delegators can vote but validators as well, and the strategy is modifiable
- Calculate validators vote as well
- Using graph requests
- Add params to turn on/off validators vote
Please review it and let me now your thoughts!
Thanks!

[skale-delegation-weighted] Improve skale delegation weighted strategy

---

src/strategies/erc4626-assets-of/README.md
src/strategies/erc4626-assets-of/examples.json
src/strategies/erc4626-assets-of/index.ts
src/strategies/erc4626-assets-of/schema.json
src/strategies/index.ts

[ERC4626](https://ethereum.org/en/developers/docs/standards/tokens/erc-4626/) is a vault standard.
Accounts can own vault tokens ("shares") representing their ownership in the vault. The vault itself holds underlying assets that those shares have claim to.
`erc20-balance-of` is a useful strategy if you want to determine the number of vault "shares" (tokens) an address has.
If, however, you want to determine the representative "assets" (underlying tokens owned by the vault) attributable to an account, you need to convert "shares" into "assets".
The result of the `balanceOf` call is fed into a subsequent `convertToAssets` call, both provided by the ERC4626 standard.
The specific usecase that I have is an auto-compounder vault that holds and buys a particular governance token. As it …

[erc4626-assets-of] Adds `erc4626-assets-of` strategy

---

src/strategies/gelato-staking/README.md
src/strategies/gelato-staking/examples.json
src/strategies/gelato-staking/index.ts
src/strategies/gelato-staking/schema.json
src/strategies/index.ts

- Add a strategy that uses the Gelato Network staking contract 
To avoid double voting, the strategy only allows the manager to vote if the staker has set one.

[gelato-staking] add gelato-staking strategy

---

src/strategies/sablier-v2/README.md
src/strategies/sablier-v2/configuration.ts
src/strategies/sablier-v2/examples.json
src/strategies/sablier-v2/index.ts
src/strategies/sablier-v2/queries.ts
src/strategies/sablier-v2/schema.json

Adds two new sub-strategies (policies) to the sablier-v2 voting strategy.
- `reserved-recipient`: adds the ability to take into account unstreamed tokens (future unlocks) as voting power alongside already available (presently withdrawable) tokens
- `unstreamed-recipient`: counts only funds that have not been streamed yet (future unlocks)

[sablier-v2] feat: add two new sub-strategies

---

src/strategies/erc20-balance-of/index.ts
src/strategies/karma-discord-roles/examples.json
src/strategies/karma-discord-roles/index.ts

- Use the Snapshot block to get the timestamp.
- Accept addresses and Snapshot block timestamp in the API URL.
- Set the score = 0, if the address doesn't have the criteria.

[karma-discord-roles] update karma-discord-roles strategy

---

src/utils.ts

Related to https://github.com/snapshot-labs/score-api/issues/839
When user is requesting a strategy which does not exist, it throws a cryptic error
```
TypeError: Cannot read properties of undefined (reading 'strategy')
File "/workspace/build/src/methods.js", line 31, in getVp
const result = await strategies_1.default.utils.getVp(params.address, params.network, params.strategies, params.snapshot, params.space,  {snip}
File "/workspace/build/src/ee.js", line 16, in <anonymous>
eventEmitter.emit(key, await action(...args));
...
(2 additional frame(s) were not displayed)
```
We should check for strategy existence before processing, and throw a more descriptive errors when strategy name is not valid
- Check for strategy validity before use
- Throw descriptive error message when strategy name …

fix: catch and throw meaningful error on non-existing startegy

---

src/strategies/dss-vest-unpaid/README.md
src/strategies/dss-vest-unpaid/examples.json
src/strategies/dss-vest-unpaid/index.ts
src/strategies/dss-vest-unpaid/schema.json
src/strategies/index.ts

This PR adds a strategy that allows voters to vote based on vested but yet unclaimed tokens in a [DssVest](https://github.com/makerdao/dss-vest) token vesting contract.
This will be used by Mangrove DAO. We use a variant of DssVest for vestings, but think that a more general strategy might be useful to others.

[dss-vest-unpaid] Add DssVest dss-vest-unpaid strategy

---

src/strategies/sablier-v2/index.ts
src/strategies/sablier-v2/queries.ts

For a snapshot that targets the `latest` block, the current live block may be out of sync with the latest one indexed by the subgraph (especially for fast L2s like Optimism). 
This PR introduces a new `getLatestBlock` utility that fetches the last block indexed by the subgraph and uses that whenever the snapshot specifies `latest`. This makes sure both subgraph and RPC multicalls are against the same state and point in time (fixing the edge-case from https://github.com/snapshot-labs/snapshot-strategies/pull/1308).

fix: sablier-v2 latest block sync [sablier-v2]

---

src/strategies/dss-vest-unpaid/index.ts

This PR fixes an issue in the `dss-vest-unpaid` strategy: The snapshot/blockTag was not passed to one of the contract calls which therefore always used `latest`.

[dss-vest-unpaid] Add missing blockTag to vesting contract call

---

src/strategies/erc1155-all-balances-of/index.ts

Related to ticket https://discord.com/channels/707079246388133940/1163294116680052849
When using the `erc1155-all-balances-of` strategy with a network not available on the subgraph, it fails with `Only absolute URLs are supported` error.
On unsupported network, there are no subgraph url, thus the error.
We should fail fast, and throw an error when the subgraphURL is empty

fix: throw an error when the network is not supported

---

src/strategies/index.ts
src/strategies/station-constant-if-badge/README.md
src/strategies/station-constant-if-badge/examples.json
src/strategies/station-constant-if-badge/index.ts
src/strategies/station-constant-if-badge/schema.json

_This PR depends on https://github.com/snapshot-labs/snapshot-strategies/pull/1316._
This PR adds the `station-constant-if-badge` strategy. The strategy returns a constant if a voter/proposer has a specific badge in a [Station](https://www.station.express/) [GroupOS](https://groupos.xyz/) group; If not, zero is returned.
This strategy can be used as a validation strategy that only allows certain members to vote/propose.
This strategy will be used by [Mangrove DAO's](https://www.mangrove.exchange/) multistakeholder governance.

[station-constant-if-badge] Add Station GroupOS validation strategy for members with a specific badge

---

src/strategies/index.ts
src/strategies/mangrove-station-qv-scaled-to-mgv/README.md
src/strategies/mangrove-station-qv-scaled-to-mgv/examples.json
src/strategies/mangrove-station-qv-scaled-to-mgv/index.ts
src/strategies/mangrove-station-qv-scaled-to-mgv/schema.json

_This PR depends on https://github.com/snapshot-labs/snapshot-strategies/pull/1316 and https://github.com/snapshot-labs/snapshot-strategies/pull/1315._
This PR adds the `mangrove-station-qv-scaled-to-mgv` strategy. The strategy allows active members of one of [Mangrove DAO's](https://www.mangrove.exchange/) governance groups (Builders Group and Pods Group) to vote in the Mangrove multistakeholder governance.
Quadratic voting is applied to each member's score and then the voting weight is scaled such that the total voting weight of the group is equal to the circulating supply of MGV tokens. This ensures that the three stakeholder groups have equal voting weights.
Mangrove DAO governance groups are [Station](https://www.station.express/) [GroupOS](https://groupos.xyz/) groups on-chain, and …

[mangrove-station-qv-scaled-to-mgv] Add Mangrove Station GroupOS voting strategy

---

src/strategies/floki/README.md
src/strategies/floki/examples.json
src/strategies/floki/index.ts
src/strategies/floki/schema.json
src/strategies/index.ts

Added Floki strategy.
It combines users' FLOKI balance, as well as their staked balance on our Staking Pool, with stake multipliers taken into account (which depends on how long they staked for).
One single user wallet can have multiple stakes, so we first call `getUserStakes(address)` in the pool contract. Each user stake can have different amounts and durations, which results in different multipliers.
Next, we use the `applyMultiplier` function from the multiplier contract for each stake to find the actual balance to be considered.
Finally, we add them to the FLOKI balance.

[floki] add floki strategy

---

src/validations/passport-gated/examples.json
src/validations/passport-gated/index.ts
src/validations/passport-gated/schema.json

The Gitcoin passport team requested to update the `stamps` property as an optional parameter in the `passport-gated` validation strategy.
- Make `stamps` property as optional parameter
- Update `operator` parameter to fit different scenarios
- Update unit tests
Related PRs in other repos:
- https://github.com/snapshot-labs/snapshot/pull/4279

[passport-gated]: update required parameters

---

src/strategies/clipper-staked-sail/README.md
src/strategies/clipper-staked-sail/examples.json
src/strategies/clipper-staked-sail/index.ts
src/strategies/index.ts

Fixes # 
- Add clipper-staked-sail strategy

[clipper-staked-sail] add clipper-staked-sail strategy

---

src/strategies/cake/examples.json
src/strategies/cake/index.ts

-  Now cake strategy will only count for veCake balance after bsc block `34371669`

[cake] Update cake strategy for only veCake

---

src/strategies/index.ts
src/strategies/sd-vote-boost-twavp-vsdtoken/README.md
src/strategies/sd-vote-boost-twavp-vsdtoken/examples.json
src/strategies/sd-vote-boost-twavp-vsdtoken/index.ts

Fixes # .
Changes proposed in this pull request: add a new Stake DAO strategy for our vsdToken contract

Vsdtoken [sd-vote-boost-twavp-vsdtoken]

---

src/strategies/index.ts
src/strategies/vendor-v2-borrower-collateral-balance-of/README.md
src/strategies/vendor-v2-borrower-collateral-balance-of/examples.json
src/strategies/vendor-v2-borrower-collateral-balance-of/index.ts
src/strategies/vendor-v2-borrower-collateral-balance-of/schema.json

- Adding a new strategy for borrower collateral locked in a given vendor pool.

[vendor-v2-borrower-collateral-balance-of] feat: add vendor-v2-borrower-collateral-balance-of

---

src/strategies/sablier-v2/configuration.ts

This PR performs a cleanup on the Sablier configuration file and adds a few new networks: base, polygon, scroll, sepolia and optimism-sepolia.

[sablier-v2] chore: add new networks to sablier, cleanup config

---

src/strategies/index.ts
src/strategies/minime-balance-vs-supply-weighted/README.md
src/strategies/minime-balance-vs-supply-weighted/examples.json
src/strategies/minime-balance-vs-supply-weighted/index.ts

Fixes # .
- Add a new strategy 'minime-balance-supply-weighted'
- combination of contract-call + erc20-balance-of-weighted
- gets total supply of token, divides address' balance of tokens by the supply of the token
- applies weight to quotient for final voting power

[minime-balance-vs-supply-weighted] add minime-balance-supply strategy - giveth

---

src/strategies/giveth-gnosis-balance-supply-weighted-v3/README.md
src/strategies/giveth-gnosis-balance-supply-weighted-v3/examples.json
src/strategies/giveth-gnosis-balance-supply-weighted-v3/index.ts
src/strategies/index.ts

Fixes # .
- Add new strategy giveth-gnosis-balance-supply-weighted-v3 strategy forked from giveth-gnosis-balance-v2
- Does everything in the previous strategy + fetches circulating supply of GIV token from an API
- result is the balance of GIV on Gnosis divided by the circulating supply then multiplied by a weight

[giveth-gnosis-balance-supply-weighted-v3] add giveth-gnosis-balance-supply-weighted-v3 strategy

---

src/strategies/giveth-balances-supply-weighted/README.md
src/strategies/giveth-balances-supply-weighted/examples.json
src/strategies/giveth-balances-supply-weighted/index.ts
src/strategies/index.ts

Fixes # .
- This adds the giveth-balances-supply-weighted strategy
- Fetches balance of token
- Fetches user's balance of tokens staked in contract
- Adds staked balance and token balance together
- gets circulating supply of token from API and divides it by the token balance sum
- applies weight to final result

[giveth-balances-supply-weighted] add giveth balances supply weighted strategy 

---

src/strategies/minime-balance-vs-supply-weighted/index.ts

Fixes # .
- formatUnits on result of calling totalSupply to token contract
- parseFloat to get number 
- divide balance by result of formatted total Supply

[minime-balance-vs-supply-weighted] - formatUnits fix on totalSupply result

---

src/strategies/lrc-l2-nft-balance-of/README.md
src/strategies/lrc-l2-nft-balance-of/examples.json
src/strategies/lrc-nft-search-mult/README.md
src/strategies/lrc-nft-search-mult/examples.json

Updates both of these strategies to use/suggest the latest subgraph URL for Loopring queries.
Strategies updated in this pull request:
- lrc-nft-search-mult
- lrc-l2-nft-balance-of

[lrc-l2-nft-balance-of]chore(Loopring): Update to latest query URL

---

src/strategies/index.ts
src/strategies/whitelist-weighted-json/README.md
src/strategies/whitelist-weighted-json/examples.json
src/strategies/whitelist-weighted-json/index.ts

Adds a new strategy to circumvent the max limit of the whitelist-weighted strategy
-  Add a new strategy called whitelist-weighted-json strategy. The strategy uses a hosted json file that will allow bigger whitelists to be sent

[whitelist-weighted-json] New strategy

---

src/strategies/safe-vested/examples.json
src/strategies/safe-vested/index.ts

This PR improves calculation complexity, making the strategy faster:
- **Allocations Map**: Builds an allocations map in memory once (takes approximately 50ms).
- **Efficient Lookups**: Use the map for retrieving allocations during calculations. For 5000+ addresses, this reduces execution time by around 20 seconds.
- **Optimised Result Construction**: Avoids creating new objects at every step of the result reducer, using simple assignment instead. For +5000 addresses, this saves around 7 seconds.
An additional optimization to discuss with the SAFE team involves the size of the allocations file, currently around 120MB and loaded each time the strategy runs. We were able to trimmed it to approximately 17MB. Two possible options to optimize this:
1. Source the trimmed file alongside the …

[safe-vested] Optimize Strategy: safe-vested 

---

src/strategies/safe-vested/index.ts

It loads the allocations JSON once and stores a trimmed version in cache using a global variable inside the strategy file.

[safe-vested] cache allocations

---

src/strategies/split-delegation/README.md
src/strategies/split-delegation/examples.json
src/strategies/split-delegation/index.ts

In response to some feedback, we've made the overriding of delegate votes by the delegator configurable in the strategy params. This PR updates the api call and the README/example to include this.

[split-delegation] API request body schema update, update README and example

---

src/strategies/index.ts
src/strategies/staking-balance-of-v1/README.md
src/strategies/staking-balance-of-v1/examples.json
src/strategies/staking-balance-of-v1/index.ts
src/strategies/staking-balance-of-v1/schema.json

adding a custom staking-balance-of-v1 method that allows to track staked tokens for voting power.
Voting power is be weighed by the lockup period of a staking pool
Reasoning:
- contract_call is not possible, due to the 2 step logic necessary to retrieve the correct amount of staked tokens for a wallet
- the new strategy allows to track 5 staking pools "in one go" to improve performance and reducing the amount of requests.
- differs from 'staking-balance-v2' in the way underlying smart contracts provide interfaces for input and return values, though idea is similar.
ℹ️ This PR was created to move `staking-balance-of-v1` to a dedicated PR as requested by @ChaituVR. It was originally shared in [PR1489](https://github.com/snapshot-labs/snapshot-strategies …

[staking-balance-of-v1] New strategy staking balance v1

---

src/strategies/garden-stakes/README.md
src/strategies/garden-stakes/examples.json
src/strategies/garden-stakes/index.ts
src/strategies/garden-stakes/schema.json
src/strategies/index.ts

- Add garden-staker strategy which uses votes from garden staker contract  to calculate the vote power.
Getting the votes from the contract is not straightforward. First, we need to fetch the nonce of the user in the contract, which represents the number of stakes the user has. Then, we calculate an ID called stakeId, which is the hash of the user address and the nonce. Finally, we can get the user's votes by calling the `stakes` function with the stakeId. Users can have multiple stakes, so we need to iterate over all the stakes to get the total votes of the user.

[garden-stakes] Add garden-stakes strategy

---

src/strategies/index.ts
src/strategies/rocketpool-node-operator-delegate-v4/README.md
src/strategies/rocketpool-node-operator-delegate-v4/examples.json
src/strategies/rocketpool-node-operator-delegate-v4/index.ts

With our Houston upgrade, we are changing our Snapshot strategy to reflect our on-chain governance.
Apologies, I somehow closed the last pull request.

[rocketpool-node-operator-delegate-v4] Added the rocket-pool-node-operator-delegate-v4 strategy

---

src/strategies/decentraland-estate-size/index.ts
src/strategies/decentraland-rental-lessors/examples.json
src/strategies/decentraland-rental-lessors/index.ts
src/strategies/decentraland-wearable-rarity/index.ts

- added delay between subgraphs requests so that they don't exceed 30 per second between the three strategies
- update decentraland-rental-lessors example

chore: ratelimit decentraland strategies [decentraland-wearable-rarity]

---

src/strategies/streamr/README.md
src/strategies/streamr/examples.json
src/strategies/streamr/schema.json

- Streamr strategy should include a symbol that explains (e.g. in the SpaceProposalPage and ModalVote) what strategy contributed to the votes. So instead of just "30" it would say "30 DATA (operator)".

[streamr] added customizable symbol to strategy

---

src/strategies/candy-lockv1-token/README.md
src/strategies/candy-lockv1-token/examples.json
src/strategies/candy-lockv1-token/index.ts
src/strategies/candy-lockv1-token/schema.json
src/strategies/index.ts

New strategy for the Candy token lock v1 contracts in the Candy Defi , it returns the balances of the locked Candy tokens.

[candy-lockv1-token] feat: Add candy-lockv1-strategy

---

src/strategies/delegatexyz-erc721-balance-of/README.md
src/strategies/delegatexyz-erc721-balance-of/constants.ts
src/strategies/delegatexyz-erc721-balance-of/index.ts

Patches an exploit where users could multiply their voting power per asset by delegating to multiple wallets.
- Check outgoing delegations for each delegator (vault) address.
- Create an 'allowlist' containing the most recent delegation (hot wallet) addresses for each delegator.
- Ensure wallet is included in 'allowlist' before assigning it to the mapping and calculating voting power.
- Update README to explain the restriction to only use most recent delegate.

patch [delegatexyz-erc721-balance-of] delegatexyz-erc721-balance-of

---

src/strategies/erable-governance-v1/README.md
src/strategies/erable-governance-v1/examples.json
src/strategies/erable-governance-v1/index.ts
src/strategies/erable-governance-v1/schema.json
src/strategies/index.ts

Fixes: N/A
- Added a new custom strategy for Erable Governance, called erable-governance-v1.
- This strategy computes voting power based on the token balances of users, both from their wallets and from staked balances, where staked tokens receive a 2x voting multiplier.
- Strategy follows the ERC20 token balance format.

[erable-governance-v1] Add erable-governance-v1 strategy

---

src/strategies/index.ts
src/strategies/polygon-self-staked-pol/README.md
src/strategies/polygon-self-staked-pol/examples.json
src/strategies/polygon-self-staked-pol/index.ts
src/strategies/polygon-self-staked-pol/schema.json

This strategy calculates the voting power based on the active stake of delegators for the Polygon network

[polygon-self-staked-pol] New strategy: polygon-self-staked-pol

---

src/utils.ts

Abort fetch in customFetch on timeout
- Add a new file at root level
```node
const http = require('http'),
port = 3030,
hostname = 'localhost';
http
.createServer(async (req, res) => {
// wait for 30 seconds before responding
await new Promise((resolve) => {
setTimeout(() => {
resolve();
}, 30000);
});
res.writeHead(200, { 'Content-Type': 'application/json' });
console.log('Request received');
res.write(
JSON.stringify({
score: [
{
address: '0x1234567890abcdef1234567890abcdef12345678',
score: '100'
}
]
})
);
res.end();
})
.listen(port, hostname, () => {
// Callback for .listen, tells us when the server starts listening for requests
console.log(`Listening on ${hostname}:${port}`);
});
```
- Edit `test/strategy-with-params.test.ts`
```ts
// To test strategies by copy pasting score API body …
```

fix: Abort fetch in customFetch on timeout

---

src/strategies/decentraland-wearable-rarity/index.ts

The Graph will add query checkers eventually so this query won't be valid at that point.
- Fix dcl wearable rarities query by using `Enum`s instead of strings where they should be used
Errors with the current query:

[decentraland-wearable-rarity] feat: use enums instead of strings in graphql queries

---

src/strategies/index.ts
src/strategies/world-liberty-financial-erc20-balance-of-votes/README.md
src/strategies/world-liberty-financial-erc20-balance-of-votes/examples.json
src/strategies/world-liberty-financial-erc20-balance-of-votes/index.ts
src/strategies/world-liberty-financial-erc20-balance-of-votes/schema.json

- Added WLFI's voting strategy, which uses a custom function `balanceOfVotes`
- All tests are passing for the new strategy, which is called `world-liberty-financial-erc20-balance-of-votes`

[world-liberty-financial-erc20-balance-of-votes] added WLFI voting strategy for untransferable tokens

---

src/strategies/index.ts
src/strategies/staking-amount-duration-exponential/README.md
src/strategies/staking-amount-duration-exponential/examples.json
src/strategies/staking-amount-duration-exponential/index.ts
src/strategies/staking-amount-duration-exponential/schema.json
src/strategies/staking-amount-duration-linear/README.md
src/strategies/staking-amount-duration-linear/examples.json
src/strategies/staking-amount-duration-linear/index.ts
src/strategies/staking-amount-duration-linear/schema.json

Fixes # .
- staking-amount-duration-exponential
- staking-amount-duration-linear

[staking-amount-duration-exponential] 2 new strategies needed for our project

---

.env.example
src/strategies/index.ts
src/strategies/moxie/README.md
src/strategies/moxie/examples.json
src/strategies/moxie/index.ts

- Adding a custom strategy for calculating moxie voting power which involves multiple subgraphs and RPC Calls for Moxie Token
- Adding Moxie as a strategy in the list of strategies

[moxie] Adding Strategy For Moxie Voting Power Calculation

---

.env.example
src/strategies/moxie/index.ts

Fixes #1604 
- Adding the subgraph IDs as constants

hardcoding the subgraph ids and refactoring

---

.env.example
src/strategies/moxie/examples.json
src/strategies/moxie/index.ts

Adding a custom strategy for calculating moxie voting power which now make api call to moxie server. This is done to handle delegation & enable scalablity.

[moxie] Moxie DAO voting strategy

---

src/strategies/polygon-self-staked-pol/index.ts

Ensures the addresses are unique to avoid wrong VP calculations.

[polygon-self-staked-pol] Make addresses unique

---

src/validations/arbitrum/README.md
src/validations/passport-gated/README.md

This pull request addresses two typos found in the documentation files. These errors are important to correct for clarity and accuracy.
1. **Fixed a typo in `src/validations/arbitrum/README.md`:**
- **Before**: "**Arbitrum use an EXCLUDE_ADDRESS** (0x00000000000000000000000000000000000A4B86)"
- **After**: "**Arbitrum uses an EXCLUDE_ADDRESS** (0x00000000000000000000000000000000000A4B86)"
- **Reason**: The verb "use" is incorrect here and should be "uses" to match the subject "Arbitrum" (third-person singular).
2. **Fixed a typo in `src/validations/passport-gated/README.md`:**
- **Before**: "to evaluate if an address is eligible for creating/voting on a proposa"
- **After**: "to evaluate if an address is eligible for creating/voting on a proposal"
- **Reason**: The word "proposa" is a …

Typos found in the documentation files

---

src/strategies/botto-dao/README.md
src/strategies/brightid/README.md
src/strategies/streamr/README.md

1. src/strategies/botto-dao/README.md
- liquidiy mining program
+ liquidity mining program
Reason: Fixed spelling error in the word "liquidity" to maintain correct technical terminology.
2. src/strategies/brightid/README.md
- has no interest on setting
+ has no interest in setting
Reason: Corrected preposition usage from "on" to "in" to follow proper English grammar rules for the phrase "interest in".
3. src/strategies/streamr/README.md
- help making that stream
+ help make that stream
Reason: Improved verb form usage by removing gerund "making" after "help" to follow standard English grammar rules.

Fix Grammar and Spelling Issues in Strategy Documentation

---

src/strategies/index.ts
src/strategies/morpho-delegation/README.md
src/strategies/morpho-delegation/examples.json
src/strategies/morpho-delegation/index.ts
src/strategies/morpho-delegation/schema.json

Adds the morpho-delegation strategy that enables any token that inherits from Morpho Labs `DelegationToken` contract to get holders delegated voting power.

[morpho-delegation] morpho-delegation strategy

---

src/strategies/index.ts
src/strategies/realt/README.md
src/strategies/realt/examples.json
src/strategies/realt/index.ts
src/strategies/realt/schema.json

This pull request introduces a new strategy called `realt` to the project. The changes include the implementation of the strategy, documentation, and example usage. Below are the most important changes:
* [`src/strategies/index.ts`](diffhunk://#diff-ffbd911cea05f2f45f79a8322799384941a6f4d2b49333ebc746229235418891R471): Imported the `realt` strategy and added it to the `strategies` object. [[1]](diffhunk://#diff-ffbd911cea05f2f45f79a8322799384941a6f4d2b49333ebc746229235418891R471) [[2]](diffhunk://#diff-ffbd911cea05f2f45f79a8322799384941a6f4d2b49333ebc746229235418891L949-R951)
* [`src/strategies/realt/index.ts`](diffhunk://#diff-f2463b11a092fe6549ab3f9d6c9a09870b0350ed17a612526599c3b6b3c9228aR1-R51): Implemented the `realt` strategy, which calculates the balances of voters for a specific …

[realt] feat: realt

---

src/strategies/index.ts
src/strategies/synapse/README.md
src/strategies/synapse/examples.json
src/strategies/synapse/index.ts
src/strategies/synapse/schema.json

Synapse multichain strategy addition. 
Adds support for Staked SYN across supported chains as well as SYN on the supported chains. 
Supported chains: 
- Ethereum (ETH)
- Arbitrum (ARB)
- Avalanche (AVAX)
- Optimism (OP)
- BNB Chain (BSC)
- Polygon (MATIC)
- Base

[synapse] strategy addition

---

src/strategies/index.ts
src/strategies/spooky-lp-sonic/README.md
src/strategies/spooky-lp-sonic/examples.json
src/strategies/spooky-lp-sonic/index.ts

This pull request introduces a new strategy called `spooky-lp-sonic` for calculating liquidity positions in $BOO pools. The changes include adding the new strategy to the list of strategies, creating a README file for documentation, providing example queries, and implementing the strategy logic.
* **Strategy Addition:**
* Added `spooky-lp-sonic` to the list of strategies in `src/strategies/index.ts`.
* **Documentation:**
* Created `src/strategies/spooky-lp-sonic/README.md` to document the new strategy, including an overview of the pools queried and the method used to calculate net liquidity.
* **Example Queries:**
* Added `src/strategies/spooky-lp-sonic/examples.json` to provide example queries for the new strategy.
* **Strategy Logic:**
* Implemented the `spooky-lp-sonic` strategy in …

[spooky-lp-sonic] Added spooky-lp-sonic strategy and updated index.ts

---

src/validations/passport-gated/index.ts

Fixes https://github.com/snapshot-labs/workflow/issues/456
The scoreThreshold was defaulted to `0` previously but later updated to be a required field
https://github.com/snapshot-labs/snapshot-strategies/commit/2615e58789c21757e89f2427009bdfe6c2b576f9
But some spaces are not updating space settings for their reasons, this PR will default it to `0` like before

[passport-gated] fix: default scoreThreshold to 0

---

src/strategies/index.ts
src/strategies/puffer-getpastvotes/README.md
src/strategies/puffer-getpastvotes/examples.json
src/strategies/puffer-getpastvotes/index.ts
src/strategies/puffer-getpastvotes/schema.json
src/strategies/shroomy-voting-power/index.ts

Create a new voting strategy that uses `getPastVotes` from ERC20Votes.

[puffer-getpastvotes] Puffer erc20-votes strategy

---

src/strategies/defi-app-voting/README.md
src/strategies/defi-app-voting/examples.json
src/strategies/defi-app-voting/index.ts

- Adjusted multiplier for HOME and sHOME voting
- Improved README
- Updated example with live contracts

[defi-app-voting] fix: updated defi-app-voting strategy

---

src/utils.ts

Fix the missing `getFormattedAddress` function re-export

fix: export getFormattedAddress from snapshot.js (#1756)

---

src/utils/vp.ts

Fix an issue where it's expecting the 'strategies' params to define the supported protocols.
The `supportedProtocols` should come from the hardcoded property from the strategy ifself

fix: get strategies supported protocols from strategy module

---

src/utils/vp.ts

Similar to https://github.com/snapshot-labs/snapshot-strategies/pull/1759

fix: get supported protocols from hardcodes strategy module

---

src/strategies/index.ts
src/strategies/xaqua-vaults-treasury/examples.json
src/strategies/xaqua-vaults-treasury/index.ts

Fixes # .
This PR adds a custom Snapshot voting strategy named xaqua-vaults-treasury.
The strategy aggregates voting power for a user by summing their balances from:
Two staking vaults (via balanceOf(address))
A treasury contract (via usersAllocation(address))
Calculations:
votingPower = vault1.balanceOf(address)
+ vault2.balanceOf(address)
+ treasury.usersAllocation(address)

[xaqua-vaults-treasury] Add xaqua-vaults-treasury strategy
