snapshot-labs/snapshot-strategies

src/strategies/cake/index.ts

- Adds minimum voting power to fix issues with our subgraph

[cake] feat(cake): Minimum voting power

---

package-lock.json
package.json
scripts/textToJson.ts
src/strategies/cake/index.ts
test/index.spec.ts
test/scores.ts

TSC build fixes

---

src/strategies/biswap/README.md
src/strategies/biswap/examples.json
src/strategies/biswap/index.ts
src/strategies/index.ts

- Balances: auto compound, pool BSW - BSW, farm BSW - BNB and BSW USDT, launchpools, token

[biswap] Add biswap strategy

---

src/strategies/sushiswap/README.md
src/strategies/sushiswap/examples.json
src/strategies/sushiswap/index.ts

This improved strategy also uses the balances of the LP tokens sent to the Master Chef contract

[sushiswap] Optionally use staked LP tokens

---

src/strategies/egl-vote/README.md
src/strategies/egl-vote/examples.json
src/strategies/egl-vote/index.ts
src/strategies/index.ts

[egl-vote] Add the egl vote strategy

---

src/strategies/honeyswap/README.md
src/strategies/honeyswap/examples.json
src/strategies/honeyswap/index.ts
src/strategies/index.ts

Fixes # .
-  Added Honeyswap strategy

[honeyswap] Added Honeyswap strategy

---

src/strategies/erc721-multi-registry/README.md
src/strategies/erc721-multi-registry/examples.json
src/strategies/erc721-multi-registry/index.ts

- change parameters into an object
- add symbol at the root of the object

[erc721-multi-registry] fix erc721-multi-strategy parameters

---

src/strategies/meebitsdao/README.md
src/strategies/meebitsdao/examples.json

Fixes # .
- Fix example and readme in meebitsdao strategy

[meebitsdao] Fix example and readme in meebitsdao strategy

---

src/strategies/crucible-erc20-balance-of/examples.json

[crucible-erc20-balance-of] Add symbol in example params

---

src/strategies/index.ts
src/strategies/mcn-farm/README.md
src/strategies/mcn-farm/examples.json
src/strategies/mcn-farm/index.ts

This is the custom strategy for MCN Ventures.
MCN tokens must be staked in the [farm](https://farm.mcn.ventures) to have voting power. LP tokens and pending reward tokens are also counted for voting.

[mcn-farm] Add mcn-farm strategy

---

src/strategies/dfyn-staked-in-vaults/README.md
src/strategies/dfyn-staked-in-vaults/examples.json
src/strategies/dfyn-staked-in-vaults/index.ts
src/strategies/index.ts

Fixes # .
- new strategy added to check score for dfyn staked in dfyn vaults

[dfyn-staked-in-vaults] dfyn-staked-in-vaults strategy added

---

src/strategies/dfyn-staked-in-vaults/index.ts

Fixes # .
- Solved an issue with summation code, for more than two summations, add function from the BigNumber library was giving some issues.

[dfyn-staked-in-vaults] Update dfyn-staked-in-vaults index.ts

---

src/strategies/crucible-erc20-balance-of/examples.json
src/strategies/crucible-erc20-balance-of/index.ts

[crucible-erc20-balance-of] Update - Edge Case Resolution - Padding Addresses

---

src/strategies/faraland-staking/examples.json
src/strategies/faraland-staking/index.ts
src/strategies/index.ts

adding strategy snapshot staking balance on faraland.io contract

[faraland-staking] add fara staking strategy

---

src/strategies/dextf-staked-in-vaults/README.md
src/strategies/dextf-staked-in-vaults/examples.json
src/strategies/dextf-staked-in-vaults/index.ts
src/strategies/index.ts

Strategy to calculate number of staked DEXTF

[dextf-staked-in-vaults] DEXTF: staked tokens

---

src/strategies/index.ts
src/strategies/sunrisegaming-staking/README.md
src/strategies/sunrisegaming-staking/examples.json
src/strategies/sunrisegaming-staking/index.ts

Add sunrisegaming-staking strategy
- Total token in staking pool

[sunrisegaming-staking] Add sunrisegaming-staking strategy

---

src/strategies/iotex-balance/examples.json
src/strategies/iotex-balance/index.ts
src/strategies/iotex-staked-balance/index.ts

[iotex-balance] change IOTEX server URI

---

src/strategies/index.ts
src/strategies/sunrisegaming-univ2-lp/README.md
src/strategies/sunrisegaming-univ2-lp/examples.json
src/strategies/sunrisegaming-univ2-lp/index.ts

Add sunrisegaming-univ2-lp strategy
Balances of the underlying token in LP swap and staking pool

[sunrisegaming-univ2-lp] Add sunrisegaming-univ2-lp strategy

---

src/strategies/index.ts
src/strategies/single-staking-pools-balanceof/README.md
src/strategies/single-staking-pools-balanceof/examples.json
src/strategies/single-staking-pools-balanceof/index.ts

Implements new strategy to fetch Staked token amount in single staking pool
- Implementes new single-staking-pools-balanceof

[single-staking-pools-balanceof] New Strategy for Single Staking Pools

---

src/strategies/balance-in-vdfyn-vault/README.md
src/strategies/balance-in-vdfyn-vault/examples.json
src/strategies/balance-in-vdfyn-vault/index.ts
src/strategies/index.ts

Fixes # .
- added a new strategy to calculate the amount of Dfyn tokens staked in vDfyn vault
- 
-

[balance-in-vdfyn-vault] Added vdfyn strategy

---

src/strategies/cyberkongz/examples.json
src/strategies/cyberkongz/index.ts
src/strategies/index.ts

Simple strategy based off 2 erc721 contracts and an erc20 contract

[cyberkongz] Add cyberkongz strategy

---

src/strategies/index.ts
src/strategies/mstable/README.md
src/strategies/mstable/examples.json
src/strategies/mstable/index.ts

Create strategy for voting with stkMTA & stkBPT balances

[mstable] Add mStable strategy

---

src/strategies/index.ts
src/strategies/polis-balance/examples.json
src/strategies/polis-balance/index.ts

This PR adds a new strategy to count polis balance (similar to eth-balance) including validators and delegators balances.

[polis-balance] Upload polis balance strategy

---

src/strategies/uniswap-v3-staking/README.md
src/strategies/uniswap-v3-staking/helper.ts

- Added README
- Removed check for in-range V3 position. This allows out-of-range V3 positions to be considered

[uniswap-v3-staking] Uniswap v3 staking improvements

---

src/strategies/delegation/index.ts
src/strategies/erc20-balance-of-delegation/index.ts
src/strategies/erc20-balance-of-quadratic-delegation/index.ts
src/strategies/esd-delegation/index.ts
src/strategies/xdai-stake-delegation/index.ts
src/utils.ts
src/utils/delegation.ts
test/delegation.ts

Query for delegation hit the limit of 1000 results on certain space like "cvx.eth", this PR is query for 2 pages instead of 1. 
@ChaituVR Can you test these changes to be sure nothing break and get this merged ASAP?

[delegation] Fix: paginate delegation

---

src/strategies/erc20-balance-of-weighted/README.md
src/strategies/erc20-balance-of-weighted/examples.json
src/strategies/erc20-balance-of-weighted/index.ts
src/strategies/index.ts

- Adding in weighted voting power for ERC20 tokens

[erc20-balance-of-weighted] Adding a strategy that enables weighted voting power for erc20 tokens

---

src/strategies/digitalax-genesis-contribution/README.md
src/strategies/digitalax-genesis-contribution/examples.json
src/strategies/digitalax-genesis-contribution/index.ts
src/strategies/index.ts

Hello there,
Please find my new strategy for DIGITALAX here included. Please let me know if there are any changes that need to be made.
This PR conforms to the requirements and passes the test environment.
All the best
DIGITALAX Core Team

[digitalax-genesis-contribution] Digitalax Genesis Contribution

---

src/strategies/digitalax-genesis-contribution/examples.json
src/strategies/digitalax-genesis-contribution/index.ts

We need this PR in quickly as there was a need for the ETH contributions table to be converted better to MONA values

[digitalax-genesis-contribution] Changes to convert ETH Value to MONA

---

src/strategies/digitalax-lp-stakers/examples.json
src/strategies/digitalax-lp-stakers/index.ts
src/strategies/index.ts

This is for the digitalax LP stakers just for the staking contract to see how much MONA each user technically has for score

[digitalax-lp-stakers] Digitalax mainnet LP stakers strategy

---

src/strategies/digitalax-mona-quickswap/README.md
src/strategies/digitalax-mona-quickswap/examples.json
src/strategies/digitalax-mona-quickswap/index.ts
src/strategies/index.ts

Digitalax mona quickswap - you can use this to get MONA value locked into the two quickswap pools available for MONA

[digitalax-mona-quickswap] Digitalax mona quickswap

---

src/strategies/galaxy-nft-with-score/examples.json
src/strategies/galaxy-nft-with-score/index.ts
src/strategies/index.ts

1. adding galaxy-nft-with-score strategy to list of strategies.

[galaxy-nft-with-score] add strategy: galaxy-nft-with-score

---

src/strategies/galaxy-nft-with-score/examples.json
src/strategies/galaxy-nft-with-score/index.ts
src/strategies/index.ts

Fixes # .
-For [galaxy-nft-with-score], query subgraph with snapshot id.
- 
-

Fix for [galaxy-nft-with-score], query subgraph with snapshot id.

---

src/strategies/galaxy-nft-with-score/examples.json
src/strategies/galaxy-nft-with-score/index.ts
src/strategies/index.ts

Fixes:
1. [galaxy-nft-with-score] strategy variable name fix according to user request.

Fix: [galaxy-nft-with-score] strategy variable name fix according to user request.

---

src/strategies/index.ts
src/strategies/vesper/examples.json
src/strategies/vesper/index.ts

This strategy calls the `VesperVotingPower` in order to get accounts' voting power.

[vesper] Add Vesper strategy

---

src/strategies/aks/README.md
src/strategies/aks/examples.json
src/strategies/aks/index.ts
src/strategies/index.ts

Fixes # .
- A new strategy name aks with token AKS has been added 
- Tests are clearing with this strategy
-

[aks] AKS strategy

---

src/strategies/aks/index.ts
src/strategies/balancer/index.ts
src/strategies/galaxy-nft-with-score/examples.json
src/strategies/galaxy-nft-with-score/index.ts
src/strategies/multichain/index.ts

Fix linting

---

src/strategies/bsc-mvb/examples.json
src/strategies/bsc-mvb/index.ts
src/strategies/galaxy-nft-with-score/examples.json
src/strategies/galaxy-nft-with-score/index.ts
src/strategies/index.ts

Feature:
[galaxy-nft-with-score], let user input specific subgraph for querying.

[bsc-mvb] New strategy + let user input specific subgraph for querying

---

src/strategies/index.ts
src/strategies/tech-quadratic-ranked-choice/README.md
src/strategies/tech-quadratic-ranked-choice/examples.json
src/strategies/tech-quadratic-ranked-choice/index.ts

Create a new strategy for TEC Commons governance.

[tech-quadratic-ranked-choice] TECH stragegy 

---

src/strategies/index.ts
src/strategies/thales/README.md
src/strategies/thales/examples.json
src/strategies/thales/index.ts

- Create a new strategy for Thales governance.

[thales] Thales strategy

---

src/strategies/dgenesis/README.md
src/strategies/dgenesis/examples.json
src/strategies/dgenesis/index.ts
src/strategies/index.ts

[dgenesis] dGenesis Strategy 

---

src/strategies/index.ts
src/strategies/tomyumswap/README.md
src/strategies/tomyumswap/examples.json
src/strategies/tomyumswap/index.ts

Fixes # .
- New strategy with the name tomyumswap has been added
- Based on the token TOMYUM
- Minimum voting power needed: 0.1
- Voting power and subgraph endpoints have been changed
All test cases are passing

[tomyumswap] Strategy tomyumswap added

---

src/strategies/blockzerolabs-cryptonauts/README.md
src/strategies/blockzerolabs-cryptonauts/examples.json
src/strategies/blockzerolabs-cryptonauts/index.ts
src/strategies/index.ts

Added Blockzerolabs Cryptonauts voting strategy

[blockzerolabs-cryptonauts] Adding Blockzerolabs Cryptonauts Strategy

---

src/strategies/honeyswap/README.md
src/strategies/honeyswap/examples.json
src/strategies/honeyswap/index.ts

This improved strategy also uses the balances of the LP tokens sent to the HoneyFarm contract

[honeyswap] - Optionally use staked LP tokens

---

src/strategies/erc20-balance-of-contract-multiplier/README.md
src/strategies/erc20-balance-of-contract-multiplier/examples.json
src/strategies/erc20-balance-of-contract-multiplier/index.ts
src/strategies/index.ts

[erc20-balance-of-contract-multiplier] ERC20 Balance of with contract multiplier strategy

---

src/strategies/sushiswap/index.ts

This improvement allows to get more than 1000 items from the subgraphs

[sushiswap] Add pagination to subgraph requests

---

src/strategies/index.ts
src/strategies/snet-stakers/README.md
src/strategies/snet-stakers/examples.json
src/strategies/snet-stakers/index.ts

This strategy returns the staking pool balances of the voters for the SingularityNET project.

[snet-stakers] strategy: snet-stakers

---

src/strategies/index.ts
src/strategies/snet-farmers/README.md
src/strategies/snet-farmers/examples.json
src/strategies/snet-farmers/index.ts

This strategy returns the yield-farming pool balances of the voters for the SingularityNET project.

[snet-farmers] Strategy

---

src/strategies/index.ts
src/strategies/juicebox/examples.json
src/strategies/juicebox/index.ts

This strategy returns the voting power of token holders of a Juicebox powered project (identified by projectId and symbol)
Please review me carefully, I'm a new contributor to snapshot
Test results:

[juicebox] strategy

---

src/strategies/biswap/examples.json
src/strategies/biswap/index.ts

Fixes #Error in LP balance .
- Add total supply and balance for lp address
- Make user balance in lp token correct

[biswap] UPDATE: Stategy: biswap

---

src/strategies/api/index.ts

added new optional parameter "additionalParameters" THis can be used for APIs that require paremeters.
Example: api.com/api.php?module=governance&network=56&......
The optional parameter in this case is additionalParameters: "module=governance"

[api] Update index.ts

---

src/strategies/planet-finance/examples.json
src/strategies/planet-finance/index.ts

Fixes # .
- REMOVED OLD POOLS SHARES
- ADDED LENDING POOL
- ADDED TWO NEW POOLS

[planet-finance] UPDATE_VOTING-STRATEGY

---

src/strategies/coordinape/index.ts

fix: update api url [coordinape]

---

src/strategies/masterchef-pool-balance/examples.json
src/strategies/masterchef-pool-balance/index.ts

Fixes # .
- Added tokenIndex option to masterchef-pool-balance to select tokenIndex from LP pool
- Fixed tests failing

[masterchef-pool-balance] Update to masterchef-pool-balance

---

src/strategies/cronaswap/README.md
src/strategies/cronaswap/examples.json
src/strategies/cronaswap/index.ts
src/strategies/index.ts

[cronaswap] Add strategy for CronaSwap

[cronaswap] Add strategy for CronaSwap

---

src/strategies/genart/examples.json
src/strategies/genart/index.ts
src/strategies/index.ts

Added genart strategy for GEN.ART DAO. NFT membership ownership + ERC20 balance.

[genart] add genart strategy

---

src/strategies/digitalax-lp-stakers-matic/examples.json
src/strategies/digitalax-lp-stakers-matic/index.ts
src/strategies/digitalax-mona-quickswap/index.ts
src/strategies/index.ts

Fixes # .
- This PR is created again to separate strategies
- 
-

[digitalax-lp-stakers-matic] lp stakers on matic

---

src/strategies/index.ts
src/strategies/squid-dao/README.md
src/strategies/squid-dao/examples.json
src/strategies/squid-dao/index.ts
src/strategies/squid-dao/schema.json

Adds voting strategy for SquidDAO, combining NFT holders and vewsSquid holders.

[squid-dao] Add squid-dao strategy

---

src/strategies/digitalax-mona-stakers-matic/examples.json
src/strategies/digitalax-mona-stakers-matic/index.ts
src/strategies/index.ts

Fixes # .
- 
- Requested changes from before, split PRS
-

[digitalax-mona-stakers-matic] mona staking digitalax

---

src/strategies/index.ts
src/strategies/orange-reputation-based-voting/examples.json
src/strategies/orange-reputation-based-voting/index.ts

add orange-reputation-based-voting for orange-protocol

[orange-reputation-based-voting] add orange-reputation-based-voting

---

src/strategies/contract-call/examples.json
src/strategies/contract-call/index.ts

[contract-call] Support multiple outputs

---

src/strategies/index.ts
src/strategies/sumami-holders/index.ts
src/strategies/zorro/README.md
src/strategies/zorro/examples.json
src/strategies/zorro/index.ts
src/strategies/zorro/schema.json

Basic 1 person 1 vote strategy

[zorro] Zorro Proof of Personhood Strategy

---

src/strategies/digitalax-mona-stakers-matic/index.ts

[digitalax-mona-stakers-matic] Fix conversion of wei to eth

---

src/strategies/index.ts
src/strategies/staked-balancer/examples.json
src/strategies/staked-balancer/index.ts

Accounts for tokens held by a balancer LP strategy, weighted by the balance of the stakedBpt the addresses hold - where the staking contract is the one holding the balance of the balancer pool token.

[staked-balancer] snapshot strategy

---

src/utils/delegation.ts

official snapshot delegation subgraphs from https://github.com/snapshot-labs/snapshot-subgraph/blob/master/package.json
Fixes # .
- 
- 
-

adding the bsc and matic delegations

---

src/strategies/cyberkongz-v2/examples.json
src/strategies/cyberkongz-v2/index.ts
src/strategies/index.ts

- removed liquidity pools from cyberkongz strategy

[cyberkongz-v2] blacklist

---

src/strategies/genomesdao/README.md
src/strategies/genomesdao/examples.json
src/strategies/genomesdao/index.ts
src/strategies/genomesdao/schema.json
src/strategies/index.ts

[genomesdao] feat: strategy for genomesdao

---

src/strategies/aavegotchi-agip-17/index.ts
src/strategies/aavegotchi-agip/index.ts

Add "first:1000" to gotchi subgraph query
Fixes # .
- 
- 
-

[aavegotchi-agip-17] Update index.ts

---

src/strategies/total-axion-shares/examples.json
src/strategies/total-axion-shares/index.ts

- Change data_reader_address
- Add param to change it in the future

[total-axion-shares] Update total-axion-shares strategy

---

src/strategies/erc1155-balance-of-ids-weighted/examples.json
src/strategies/erc1155-balance-of-ids/examples.json
src/strategies/erc1155-balance-of-ids/index.ts

[erc1155-balance-of-ids] Fixed erc1155-balance-of-ids and erc1155-balance-of-ids-weighted strategies

---

src/strategies/immutable-x/examples.json
src/strategies/immutable-x/index.ts
src/strategies/index.ts

- New strategy under `immutable-x`

[immutable-x] Add Immutable X strategy

---

src/utils/delegation.ts

Delegation subgraph for gnosis chain

---

src/strategies/banksy-dao/README.md
src/strategies/banksy-dao/examples.json
src/strategies/banksy-dao/index.ts
src/strategies/index.ts

- Adds support for reading a value in NFT and adding it. (Same as Sandman Finance)

Adds Banksy Farm DAO strategy [banksy-dao]

---

src/strategies/index.ts
src/strategies/ve-balance-of-at/README.md
src/strategies/ve-balance-of-at/examples.json
src/strategies/ve-balance-of-at/index.ts
src/strategies/ve-balance-of-at/schema.json

Fixes # .
- Add a strategy to query ve-like voting power from contract.

[ve-balance-of-at] Add ve-balance-of-at strategy

---

src/strategies/index.ts
src/strategies/staked-daomaker/README.md
src/strategies/staked-daomaker/examples.json
src/strategies/staked-daomaker/index.ts

* Adding the strategy
* Adding 17 wallets for the example
* Verifying that tests are passing < 10 sec. (all green lights)

[staked-daomaker] Adding DAOMaker Staking Strategy for voting

---

src/strategies/index.ts
src/strategies/staking-claimed-unclaimed/README.md
src/strategies/staking-claimed-unclaimed/examples.json
src/strategies/staking-claimed-unclaimed/index.ts

- Add strategy to collect ERC20 claimed and unclaimed balance from a staking contract to use as the voting amount
- 
-

[staking-claimed-unclaimed] adding staking-claimed-unclaimed strategy

---

src/strategies/immutable-x/index.ts

- IMX strategy client sends slices of ether keys to avoid large json bodies per paginated request

Send slices of addresses base on page size in imx strategy [immutable-x]

---

src/strategies/index.ts
src/strategies/printer-financial/examples.json
src/strategies/printer-financial/index.ts
src/strategies/printer-financial/schema.json

Strategy for Printer Financial governance voting

[printer-financial] added strategy for printer financial contracts

---

src/strategies/index.ts
src/strategies/starsharks/README.md
src/strategies/starsharks/examples.json
src/strategies/starsharks/index.ts

- add strategy for starsharks voting power.

[starsharks] add strategy for starsharks voting

---

src/strategies/ethercats-founders-series/examples.json
src/strategies/ethercats-founders-series/index.ts
src/strategies/index.ts

Added updated strategy under the correct name (plural 'S' in Founders) as not to break existing proposals using the old strategy. The old strategy was not scalable.

Added EtherCats Founders Series NFT strategy [ethercats-founders-series]

---

src/strategies/immutable-x/index.ts

- Add support to IMX strategy for requests against IMX backend with no addresses specified
- This functionality is unlikely used by snapshot.org but without this PR the logic would run forever if a request was ever made without specifying any addresses

[immutable-x] Add support for requests without addresses in json body for imx strategy

---

src/strategies/index.ts
src/strategies/ve-ribbon/README.md
src/strategies/ve-ribbon/examples.json
src/strategies/ve-ribbon/index.ts
src/strategies/ve-ribbon/schema.json

Fixes # .
- new strategy for total balance = erc20balance + locked balance in ribbon voting escrow 
- 
-

[ve-ribbon] New strategy ve-ribbon

---

src/strategies/index.ts
src/strategies/sd-boost/README.md
src/strategies/sd-boost/examples.json
src/strategies/sd-boost/index.ts

Fixes # .
-  Strategy for StakeDAO to vote with sdToken with veSDT voting boost

[sd-boost] sd-boost initial implementation

---

src/strategies/index.ts
src/strategies/ve-ribbon-voting-power/README.md
src/strategies/ve-ribbon-voting-power/examples.json
src/strategies/ve-ribbon-voting-power/index.ts
src/strategies/ve-ribbon-voting-power/schema.json

Fixes # .
- return effective voting balance of veRBN lockers
- 
-

[ve-ribbon-voting-power] verbn voting

---

src/strategies/index.ts
src/strategies/oolongswap/examples.json
src/strategies/oolongswap/index.ts

- Copies Uniswap strategy and adjust values for Oolongswap on Boba
This could in practice be added to the existing Uniswap strategy but that could cause issues if Uniswap ever expands to Boba.

[oolongswap] create strategy

---

src/strategies/index.ts
src/strategies/wanakafarm-land-ingame/examples.json
src/strategies/wanakafarm-land-ingame/index.ts

[wanakafarm-land-ingame] Add strategies wanakafarm land ingame

---

src/strategies/index.ts
src/strategies/planet-finance-v2/examples.json
src/strategies/planet-finance-v2/index.ts

Fixes # .
- Planet Finance updated voting strategy to give 5X voting power for AQUA infinity vault stakers

[planet-finance-v2] Planet V2 voting strategy

---

src/strategies/gno/examples.json
src/strategies/gno/index.ts
src/strategies/index.ts

-  Adds a voting strategy to receive voting data from the Gnosis token distributions from subgraph

[gno] GNO voting strategy

---

src/strategies/index.ts
src/strategies/starcatchers-top-window/README.md
src/strategies/starcatchers-top-window/examples.json
src/strategies/starcatchers-top-window/index.ts

- Adds new strategy for Starcatchers project

Add Starcatchers voting strategy

---

src/strategies/galaxy-nft-with-score/examples.json
src/strategies/galaxy-nft-with-score/index.ts

[Fix]: fix only 100 NFTs shows under certain contract by default

[galaxy-nft-with-score] fix only 100 NFTs shows under certain contract by default

---

src/strategies/aelin-council/examples.json
src/strategies/aelin-council/index.ts

Fixes # .
- new voting strategy for Aelin Council elections

Aelin council strategy updated [aelin-council]

---

src/strategies/genomesdao/README.md
src/strategies/genomesdao/examples.json
src/strategies/genomesdao/index.ts
src/strategies/genomesdao/schema.json

Fixes # .
- add veGNOME address
- 5x power than GNOME

[genomesdao] fix: add veGNOME to calculate the power of voting

---

src/strategies/gno/examples.json
src/strategies/gno/index.ts

- map all addresses to lower case
- return checksummed addresses

[gno] fix user id case

---

src/strategies/sd-boost/index.ts

Fixes # .
- small update for ANGLE protocol utilisation on snapshot
- 
-

version 0.0.3 [sd-boost]

---

src/strategies/erc721-with-metadata/README.md
src/strategies/erc721-with-metadata/examples.json
src/strategies/erc721-with-metadata/index.ts
src/strategies/index.ts

@ChaituVR I recreated new PR for `erc721-with-metadata`.
Please review.

[erc721-with-metadata] erc721-with-metadata

---

src/strategies/index.ts
src/strategies/uma-voting/README.md
src/strategies/uma-voting/examples.json
src/strategies/uma-voting/index.ts

Signed-off-by: Alex Gaines <againes@umaproject.org>
- Adds new uma-voting strategy

[uma-voting] add new strategy uma-voting

---

src/strategies/index.ts
src/strategies/masterchef-pool-balance-no-rewarddebt/examples.json
src/strategies/masterchef-pool-balance-no-rewarddebt/index.ts

Masterchef pool balance strategy. Differs from strategy masterchef-pool-balance by working with masterchefs that only return an amount from userInfo, not a rewardDebt.

[masterchef-pool-balance-no-rewarddebt] Add masterchef-pool-balance-no-rewarddebt

---

src/strategies/index.ts
src/strategies/proof-of-humanity/README.md
src/strategies/proof-of-humanity/examples.json
src/strategies/proof-of-humanity/index.ts
src/strategies/proof-of-humanity/schema.json

Fixes #531 
- adds a `proof-of-humanity` strategy

[proof-of-humanity] Add a new Proof of Humanity strategy

---

src/strategies/index.ts
src/strategies/squadz-power/README.md
src/strategies/squadz-power/examples.json
src/strategies/squadz-power/index.ts

Fixes # .
- Adding a new strategy for "Squadz" collections (squadz.xyz)

[squadz-power] Add Squadz-Power Strategy

---

src/strategies/erc1155-all-balances-of/README.md
src/strategies/erc1155-all-balances-of/examples.json
src/strategies/erc1155-all-balances-of/index.ts

[erc1155-all-balances-of] Fix strategy not returning all token balances

---

src/strategies/index.ts
src/strategies/stakedao-governance-update/README.md
src/strategies/stakedao-governance-update/examples.json
src/strategies/stakedao-governance-update/index.ts

Fixes # .
- create a new model including veSDT mechanism to the snapshot

version 0.0.2 [stakedao-governance-update]

---

src/strategies/samurailegends-generals-balance/README.md
src/strategies/samurailegends-generals-balance/examples.json
src/strategies/samurailegends-generals-balance/index.ts

Update the `samurailegends-generals-balance` strategy to support a multiplier
- Add multiplier
- Update ReadMe.md for clarification
- Update examples
- Change calculation strategy to be more performant with more addresses

[samurailegends-generals-balance] Update strategy with multiplication

---

src/strategies/dogs-unchained/index.ts

Prioritizes casing passed in through [addresses]

updated address casing [dogs-unchained]

---

src/strategies/index.ts
src/strategies/thresholds/README.md
src/strategies/thresholds/examples.json
src/strategies/thresholds/index.ts

[thresholds] Threshold strategy

---

.github/workflows/nodejs.yml
.github/workflows/publish.yml
.github/workflows/strategy.yml

Use yarn in all workflows

---

src/strategies/aavegotchi-agip/index.ts

- support gotchiLendings, whales

[aavegotchi-agip] support for gotchiLending

---

src/strategies/aavegotchi-agip/index.ts

Fixes issue with missing gotchi data, we are aware of open proposals and still request the update be made. thanks

[aavegotchi-agip] fix missing gotchi data with other endpoint

---

src/strategies/erc721-with-tokenid-range-weights-simple/README.md
src/strategies/erc721-with-tokenid-range-weights-simple/examples.json
src/strategies/erc721-with-tokenid-range-weights-simple/index.ts
src/strategies/erc721-with-tokenid-range-weights-simple/types.d.ts

Reverts snapshot-labs/snapshot-strategies#567

Revert "[erc721-with-tokenid-range-weights-simple] Erc721 with tokenid range weights simple v2"

---

src/strategies/cake/index.ts

- chunk the user address to avoid limitation on subgraph args

[cake] fix subgraph args limit

---

src/strategies/decentraland-estate-size/README.md
src/strategies/decentraland-estate-size/examples.json
src/strategies/decentraland-estate-size/index.ts
src/strategies/decentraland-wearable-rarity/README.md
src/strategies/decentraland-wearable-rarity/examples.json
src/strategies/decentraland-wearable-rarity/index.ts
src/strategies/index.ts

- creates `decentraland-wearable-rarity` strategy
- prevents `decentraland-estate-size` to fail if and invalid chain is selected
- adds `README` to `decentraland-estate-size`

feat: Decentraland Wearable Rarity [decentraland-wearable-rarity]

---

src/strategies/aavegotchi-agip/index.ts

strategy update for lending support

[aavegotchi-agip] strategy updates for lending

---

src/strategies/aavegotchi-agip-17/index.ts

adds batched queries to support large holders

[aavegotchi-agip-17] batch parcel queries

---

src/strategies/aavegotchi-agip/index.ts

[aavegotchi-agip] remove extra loop

---

src/strategies/minotaur-money/examples.json
src/strategies/minotaur-money/index.ts

Update MMF staking pool [minotaur-money]

---

src/strategies/index.ts
src/strategies/rowdy-roos/README.md
src/strategies/rowdy-roos/examples.json
src/strategies/rowdy-roos/index.ts

Added the Rowdy Roos voting strategy [rowdy-roos]

---

src/strategies/hedgey/README.md
src/strategies/hedgey/examples.json
src/strategies/hedgey/index.ts
src/strategies/index.ts

- Voting rights to be calculated based on the underlying tokens locked in the hedgey protocol

Hedgey strategy [hedgey]

---

src/strategies/index.ts
src/strategies/ve-balance-of-at-nft/README.md
src/strategies/ve-balance-of-at-nft/examples.json
src/strategies/ve-balance-of-at-nft/index.ts
src/strategies/ve-balance-of-at-nft/schema.json

add voting power for vedcMST NFT [ve-balance-of-at-nft]

---

src/strategies/celer-sgn-delegation/README.md
src/strategies/celer-sgn-delegation/examples.json
src/strategies/celer-sgn-delegation/index.ts

- Count the delegations to Celer SGN V2 Staking

Add SGN V2 delegations to celer-sgn-delegation [celer-sgn-delegation]

---

src/strategies/gamium-voting/index.ts

Fixes # .
- Modify simple voting strategy to weighted

[gamium] weighted voted strategy update

---

src/strategies/helix/README.md
src/strategies/helix/examples.json
src/strategies/helix/index.ts
src/strategies/index.ts

It returns the balances of the voters for HELIX token balances in Helix project(pools, farms, vaults, token).

Add Helix strategy [helix]

---

src/strategies/aavegotchi-agip/index.ts

[aavegotchi-agip] query update

---

src/strategies/earthfund-child-dao-staking-balance/README.md
src/strategies/earthfund-child-dao-staking-balance/examples.json
src/strategies/earthfund-child-dao-staking-balance/index.ts
src/strategies/earthfund-child-dao-staking-balance/schema.json
src/strategies/index.ts

Fixes # .
- Implements a new custom strategy for earthfund
- Adds the new custom strategy to the strategies index file

[earthfund-child-dao-staking-balance] Earthfund child dao staking balance custom strategy

---

src/strategies/goldfinch-voting-power/examples.json
src/strategies/goldfinch-voting-power/index.ts

- Update goldfinch voting power to account for claimable FIDU staking rewards

[goldfinch-voting-power] Account for claimable fidu staking rewards in goldfinch voting power

---

src/strategies/h2o/README.md
src/strategies/h2o/examples.json
src/strategies/h2o/index.ts
src/strategies/h2o/schema.json
src/strategies/index.ts

Fixes https://github.com/oceanprotocol/oceandao/issues/517
- Add `h2o` strategy

Add H2O strategy [h2o]

---

src/strategies/forta-shares/README.md
src/strategies/forta-shares/examples.json
src/strategies/forta-shares/index.ts
src/strategies/index.ts

- Calculates voting power based on the number of EIP 1155 shares for staked FORT

Add Forta Shares Voting Strategy [forta-shares]

---

package.json
src/strategies/erc3525-vesting-voucher/examples.json
src/strategies/erc3525-vesting-voucher/index.ts
src/strategies/erc3525-vesting-voucher/utils.ts
tsconfig.json

Also removed test folder from tsconfig

Replace prepare with postinstall and also lint fixes

---

.gitignore
src/strategies/index.ts
src/strategies/xrook-balance-of-underlying-weighted/examples.json
src/strategies/xrook-balance-of-underlying-weighted/index.ts

xROOK strategy [xrook-balance-of-underlying-weighted]

---

src/strategies/crucible-erc20-token-and-lp-weighted/README.md
src/strategies/crucible-erc20-token-and-lp-weighted/examples.json
src/strategies/crucible-erc20-token-and-lp-weighted/index.ts
src/strategies/crucible-erc20-token-and-lp-weighted/schema.json
src/strategies/index.ts

- Introduction of `crucible-erc20-token-and-lp-weighted` strategy

crucible-erc20-token-and-lp-weighted [crucible-erc20-token-and-lp-weighted]

---

src/strategies/erc20-token-and-lp-weighted/README.md
src/strategies/erc20-token-and-lp-weighted/examples.json
src/strategies/erc20-token-and-lp-weighted/index.ts
src/strategies/erc20-token-and-lp-weighted/schema.json
src/strategies/index.ts

- Introduction of `erc20-token-and-lp-weighted` strategy

erc20-token-and-lp-weighted strategy [erc20-token-and-lp-weighted]

---

src/strategies/erc20-token-and-lp-weighted/schema.json

- Update example addresses in Schema

Update `schema.json` [erc20-token-and-lp-weighted]

---

src/strategies/crucible-erc20-token-and-lp-weighted/README.md
src/strategies/crucible-erc20-token-and-lp-weighted/examples.json
src/strategies/crucible-erc20-token-and-lp-weighted/index.ts
src/strategies/crucible-erc20-token-and-lp-weighted/schema.json

- Update Variable Name
- Update Example Addresses in Schema

Updates to `crucible-erc20-token-and-lp-weighted` [crucible-erc20-token-and-lp-weighted]

---

src/strategies/digitalax-mona-quickswap/index.ts

Fixes subgraph from quickswap.info as the old subgraph was taken down in favour of a new graph ql server

Update subgraph address for uniswap quickswap code [digitalax-mona-quickswap]

---

src/strategies/erc20-balance-of/schema.json
src/strategies/index.ts
src/strategies/prepo-vesting/README.md
src/strategies/prepo-vesting/examples.json
src/strategies/prepo-vesting/index.ts
src/strategies/prepo-vesting/schema.json

- Adding new strategy for [prePO](https://prepo.io/)

feat: prepo vesting contract weighted voting [prepo-vesting]

---

src/strategies/prepo-vesting/README.md
src/strategies/prepo-vesting/index.ts

- Update prepo-vesting contract to take into consideration when vesting is paused.

Feat/update strategy [prepo-vesting]

---

src/strategies/index.ts
src/strategies/tutellus-protocol/README.md
src/strategies/tutellus-protocol/examples.json
src/strategies/tutellus-protocol/index.ts
src/strategies/tutellus-protocol/schema.json

- Added a new strategy for using it in Tutellus DAO as protocol voting strategy

Tutellus DAO protocol strategy [tutellus-protocol]

---

src/strategies/fight-club/README.md

- Minor tweaks to the README to disambiguate terminology, based on client feedback

Disambiguate "voting weight" and "weight class" [fight-club]

---

src/strategies/index.ts
src/strategies/tpro-staking/examples.json
src/strategies/tpro-staking/index.ts

tpro-staking v1.0.0 [tpro-staking]

---

src/strategies/gysr-lp-staking-balance/README.md
src/strategies/gysr-lp-staking-balance/examples.json
src/strategies/gysr-lp-staking-balance/index.ts
src/strategies/gysr-lp-staking-balance/schema.json
src/strategies/index.ts

This PR implements a strategy to get staking balances from any specified GYSR pool with LP.

[gysr-lp-staking-balance] Add GYSR Strategy

---

src/strategies/gysr-pending-rewards/examples.json

- Changing the example for the strategy.

[gysr-pending-rewards] Change example

---

src/strategies/index.ts
src/strategies/riskharbor-underwriter/README.md
src/strategies/riskharbor-underwriter/examples.json
src/strategies/riskharbor-underwriter/index.ts
src/strategies/riskharbor-underwriter/schema.json

- Strategy for underwriters in a Risk Harbor vault

Underwriter ERC721 Strategy [riskharbor-underwriter]

---

src/strategies/orbs-network-delegation/index.ts

Fixes # .
- support for chain of delegations - improve calculation
- 
-

[orbs-network-delegation] support deprecated edge case cascade delegations a->b->c

---

src/strategies/index.ts
src/strategies/synthetic-nouns-with-claimer/README.md
src/strategies/synthetic-nouns-with-claimer/examples.json
src/strategies/synthetic-nouns-with-claimer/index.ts

- Strategy for Synthetic Nouns

Synthetic Nouns Claimer Strategy [synthetic-nouns-with-claimer]

---

src/strategies/synthetic-nouns-with-claimer/examples.json
src/strategies/synthetic-nouns-with-claimer/index.ts

Fixes an issue causing scores to be dependent on input addresses case
- Checksum all addresses before use

[synthetic-nouns-with-claimer] Fix inconsistent address cases

---

src/strategies/index.ts
src/strategies/lrc-l2-nft-balance-of/README.md
src/strategies/lrc-l2-nft-balance-of/examples.json
src/strategies/lrc-l2-nft-balance-of/index.ts

- add strategy for NFT's minted on Loopring L2

Add strategy LRC NFT balances by minter account [lrc-l2-nft-balance-of]

---

src/strategies/deposit-in-sablier-stream/README.md
src/strategies/deposit-in-sablier-stream/examples.json
src/strategies/deposit-in-sablier-stream/index.ts
src/strategies/deposit-in-sablier-stream/schema.json
src/strategies/index.ts

- added strategy deposit-in-sablier-stream

add strategy deposit-in-sablier-stream [deposit-in-sablier-stream]

---

src/strategies/aavegotchi-agip-37-gltr-staked-lp/README.md
src/strategies/aavegotchi-agip-37-gltr-staked-lp/examples.json
src/strategies/aavegotchi-agip-37-gltr-staked-lp/index.ts
src/strategies/index.ts

-  This snapshot strategy enables voting power for various assets staked in GLTR staking pools as voted on by Aavegotchi DAO AGIP-37

[aavegotchi-agip-37-gltr-staked-lp] gltr-staked-lp strat

---

src/strategies/aavegotchi-agip-37-wap-ghst/README.md
src/strategies/aavegotchi-agip-37-wap-ghst/examples.json
src/strategies/aavegotchi-agip-37-wap-ghst/index.ts
src/strategies/index.ts

-  This snapshot strategy enables voting power for staked and unstaked wapGHST as voted on by Aavegotchi DAO AGIP-37

[aavegotchi-agip-37-wap-ghst] wap-ghst strat

---

src/strategies/index.ts
src/strategies/wagdie-subgraph/README.md
src/strategies/wagdie-subgraph/examples.json
src/strategies/wagdie-subgraph/index.ts

- Change Subgraph query to use `Character` entity
- Add location filtering options

Updated wagdie-subgraph strategy [wagdie-subgraph] 

---

src/strategies/delegation/examples.json
src/strategies/delegation/index.ts
src/strategies/erc20-balance-of-delegation/examples.json
src/strategies/erc20-balance-of-delegation/index.ts
test/strategy.test.ts

Strategies depend on other addresses

---

src/strategies/index.ts
src/strategies/sd-boost-delegation/README.md
src/strategies/sd-boost-delegation/examples.json
src/strategies/sd-boost-delegation/index.ts

- Add `sd-boost-delegation` strategy.

Add strategy [sd-boost-delegation]

---

src/strategies/index.ts
src/strategies/sd-boost-delegation-twavp/README.md
src/strategies/sd-boost-delegation-twavp/examples.json
src/strategies/sd-boost-delegation-twavp/index.ts

- Add `sd-boost-delegation-twavp` strategy.

Add strategy [sd-boost-delegation-twavp]

---

src/strategies/index.ts
src/strategies/single-staking-autocompound-balanceof/README.md
src/strategies/single-staking-autocompound-balanceof/examples.json
src/strategies/single-staking-autocompound-balanceof/index.ts

- Add strategy `single-staking-autocompound-balanceof`

Add strategy [single-staking-autocompound-balanceof]

---

README.md
src/strategies/anti-whale/README.md

Fix: typos

---

src/strategies/index.ts
src/strategies/posichain-staking/examples.json
src/strategies/posichain-staking/index.ts

- Add posichain-staking strategy

[posichain-staking] Add posichain-staking strategy

---

src/validations/index.ts

Reverts snapshot-labs/snapshot-strategies#926

Revert "Export examples and schema for validations"

---

src/strategies/dsla/README.md
src/strategies/dsla/examples.json
src/strategies/dsla/index.ts
src/strategies/dsla/schema.json
src/strategies/index.ts

New strategy: dsla [dsla]

---

src/strategies/otterspace-badges/examples.json
src/strategies/otterspace-badges/index.ts

The upstream subgraph was updated

Otterspace: Using updated graph model [otterspace-badges]

---

src/strategies/juicebox/examples.json
src/strategies/juicebox/index.ts

- Update juicebox strategy to include `protocolVersion` parameter
- Update examples

feature: update juicebox strategy to support other protocol versions [juicebox]

---

src/strategies/ctsi-staking/README.md
src/strategies/ctsi-staking/examples.json
src/strategies/ctsi-staking/index.ts
src/strategies/ctsi-staking/schema.json
src/strategies/index.ts

- new strategy for CTSI Staking

[ctsi-staking] new strategy for CTSI Staking

---

src/strategies/erc20-balance-of-with-delegation/README.md
src/strategies/erc20-balance-of-with-delegation/examples.json
src/strategies/erc20-balance-of-with-delegation/index.ts
src/strategies/index.ts
src/strategies/with-delegation/README.md
src/strategies/with-delegation/examples.json
src/strategies/with-delegation/index.ts
src/utils/delegation.ts

Fixes https://github.com/snapshot-labs/snapshot-strategies/issues/957

Delegation strategies to ignore override

---

src/strategies/ctsi-staking-pool/README.md
src/strategies/ctsi-staking-pool/examples.json
src/strategies/ctsi-staking-pool/index.ts
src/strategies/ctsi-staking-pool/schema.json
src/strategies/index.ts

New strategy for CTSI staking through staking pools only

[ctsi-staking-pool] new strategy for ctsi staking through pools

---

src/strategies/goldfinch-voting-power/examples.json
src/strategies/goldfinch-voting-power/index.ts

Add's a Goldfinch MembershipRewards check to see votingPower of GFI locked in vaults.

Setup MemberRewards for GoldfinchVotingPower [goldfinch-voting-power]

---

src/strategies/index.ts
src/strategies/vsta-pool-staking/README.md
src/strategies/vsta-pool-staking/examples.json
src/strategies/vsta-pool-staking/index.ts
src/strategies/vsta-pool-staking/schema.json

Add vsta-pool-staking strategy
for https://vestafinance.xyz/

[vsta-pool-staking] Add VSTA-POOL-STAKING Strategy to account for VSTA lp holders staked to our Farm contract 

---

src/strategies/babywealthyclub/examples.json
src/strategies/babywealthyclub/index.ts
src/strategies/index.ts

Fixes # .
Creates a new strategy for babywealthyclub
-  Adding babywealthyclub strategy 
babywealthyclub Project Link: https://babywealthyclub.com/

Add babywealthyclub strategy [babywealthyclub]

---

src/strategies/battlefly-vgfly-and-staked-gfly/README.md
src/strategies/battlefly-vgfly-and-staked-gfly/examples.json
src/strategies/battlefly-vgfly-and-staked-gfly/index.ts
src/strategies/index.ts

Battlefly DAO strategy consisting of:
* score for vgFLY holders
* score for gFLY stakers
* score for gFLY/Magic LP stakers (only gFLY side is counted)
Website: https://www.battlefly.game/

Battlefly DAO strategy [battlefly-vgfly-and-staked-gfly]

---

src/strategies/erc20-balance-of/examples.json

- fixed erc20-balance-of strategy test case

[erc20-balance-of] Fix: fix erc20-balance-of strategy testcase

---

src/strategies/index.ts
src/strategies/lit-dao-governance/README.md
src/strategies/lit-dao-governance/examples.json
src/strategies/lit-dao-governance/index.ts
src/strategies/lit-dao-governance/schema.json

This is a custom voting strategy for LIT DAO

Lit Dao Governance Strategy [lit-dao-governance]

---

src/strategies/wagdie-subgraph/examples.json
src/strategies/wagdie-subgraph/index.ts

- Update vote calculations to give bonus to WAGDIE NFTs if staked or seared.

[wagdie-subgraph] add: New vote weights if staked or seared.

---

src/strategies/reliquary/README.md
src/strategies/reliquary/examples.json
src/strategies/reliquary/index.ts

Adapts to changes in new Reliquary contract code.
- Change in ABI, adapt code accordingly
- Change of naming allocation points -> multiplier

[reliquary] Adapt strategy for new contract code

---

.github/workflows/validation.yml
src/validations/basic/index.ts
src/validations/index.ts
src/validations/passport-gated/index.ts
src/validations/passport-weighted/index.ts
src/validations/validation.ts
test/__snapshots__/validation.test.ts.snap
test/validation.test.ts

Related to https://github.com/snapshot-labs/snapshot/issues/3466

[basic] Add title and description to validations and add few test cases

---

src/strategies/index.ts
src/strategies/pdn-balances-and-vests/README.md
src/strategies/pdn-balances-and-vests/examples.json
src/strategies/pdn-balances-and-vests/index.ts
src/strategies/pdn-balances-and-vests/schema.json

Fixes # .
- Create a new strategy to include balances and vested amount on the voting power
- 
-

[pdn-balances-and-vests] New strategy specific for poseidon dao

---

src/strategies/erc1155-balance-of/README.md
src/strategies/erc1155-balance-of/examples.json
src/strategies/erc1155-balance-of/index.ts

- Add documentation
- Shorten Abi
- Fix test case

[erc1155-balance-of] Add documentation for erc1155-balance-of strategy

---

src/strategies/aavegotchi-agip-17/index.ts
src/strategies/aavegotchi-agip/index.ts
src/strategies/aavegotchi-wagmi-guild/index.ts

[aavegotchi-agip-17] update aavegotchi subgraph url

---

src/validations/basic/schema.json

Required for https://github.com/snapshot-labs/snapshot/pull/3634

[basic] Add schema to for basic validation

---

src/strategies/jpegd-locked-jpeg-of/README.md

[jpegd-locked-jpeg-of] Update readme

---

src/strategies/cap-voting-power/README.md
src/strategies/cap-voting-power/examples.json
src/strategies/cap-voting-power/index.ts
src/strategies/index.ts

Fixes # .
- Adds a new strategy called 'cap-voting-power' which calculates the off-chain voting power for addresses with tokens vested in a contract.

[cap-voting-power] Added cap-voting-power strategy

---

src/validations/basic/schema.json

Required for https://github.com/snapshot-labs/snapshot/pull/3775

[basic] Add schema to for basic validation 

---

src/strategies/erc721-collateral-held/README.md
src/strategies/erc721-collateral-held/examples.json
src/strategies/erc721-collateral-held/index.ts
src/strategies/erc721-collateral-held/schema.json
src/strategies/index.ts

Fixes # .
- added erc721-collateral-held for QiDao vaults

[erc721-collateral-held] Add erc721-collateral-held

---

src/strategies/battlefly-vgfly-and-staked-gfly/README.md
src/strategies/battlefly-vgfly-and-staked-gfly/examples.json
src/strategies/battlefly-vgfly-and-staked-gfly/index.ts

Upgrade for the battlefly strategy that allows voting with Battlefly founders tokens.

[battlefly-vgfly-and-staked-gfly]Feature/battlefly dao voting upgrade for founders voting

---

src/strategies/dps-nft-strategy/examples.json
src/strategies/dps-nft-strategy/index.ts
src/strategies/dps-nft-strategy/schema.json

[dps-nft-strategy] change dps-nft-strategy

---

src/strategies/hedgey-delegate/README.md
src/strategies/hedgey-delegate/examples.json
src/strategies/hedgey-delegate/index.ts
src/strategies/hedgey-delegate/schema.json
src/strategies/index.ts

Adds hedgey-delegate
This is a simple strategy to call delegatedBalances and apply a multiplier value.

[hedgey-delegate] adds strategy for hedgey vesting contracts

---

src/strategies/hedgey-delegate/examples.json
src/strategies/hedgey-delegate/index.ts
src/strategies/hedgey-delegate/schema.json

- Updates the titles on the schema.json for hedgey-delegate

fix: updates titles on schema [hedgey-delegate]

---

src/strategies/index.ts
src/strategies/spaceid/README.md
src/strategies/spaceid/examples.json
src/strategies/spaceid/index.ts
src/strategies/spaceid/schema.json

[spaceid] feat: spaceid strategy

---

src/strategies/spaceid/examples.json
src/strategies/spaceid/index.ts

[spaceid] fix: checksum address bug

---

src/strategies/otterspace-badges/index.ts

Fixes # .
- add sepolia subgraph support
- 
-

[otterspace-badges] Otterspace - adding network support for Sepolia

---

src/strategies/math/README.md
src/strategies/math/index.ts
src/strategies/math/options.ts

Fixes #1200 
- Add support for division to MATH strategy

[math] Implement divide in MATH strategy

---

src/strategies/index.ts
src/strategies/staked-morekudasai/README.md
src/strategies/staked-morekudasai/examples.json
src/strategies/staked-morekudasai/index.ts
src/strategies/staked-morekudasai/schema.json

Fixes # .
- add staked morekudasai strategy.

add staked morekudasai [staked-morekudasai]

---

src/strategies/genart/examples.json
src/strategies/genart/index.ts

consider vaulted assets for score

[genart] Fix strategy

---

src/strategies/moonbeam-free-balance/index.ts

- Supports for snapshot option when querying balance

Fixes support for snapshot block hash

---

src/strategies/index.ts
src/strategies/rocketpool-node-operator-v2/README.md
src/strategies/rocketpool-node-operator-v2/examples.json
src/strategies/rocketpool-node-operator-v2/index.ts

An update to the existing rocketpool node operator strategy however using an updated contract address.

[rocketpool-node-operator-v2] Add rocketpool node operator v2 strategy

---

src/strategies/sablier-v2/README.md
src/strategies/sablier-v2/configuration.ts
src/strategies/sablier-v2/examples.json
src/strategies/sablier-v2/index.ts
src/strategies/sablier-v2/queries.ts
src/strategies/sablier-v2/schema.json

A few QA changes for good order:

[sablier-v2] docs: polish wording in Sablier V2 README

---

src/strategies/sablier-v2/README.md

Polish wording in Sablier V2 strategy

docs: polish wording in sablier v2

---

src/strategies/pancake-profile/index.ts

Fixes # .
- Check if user is active

[pancake-profile] update strategy

---

src/strategies/erc20-balance-of-top-holders/README.md
src/strategies/erc20-balance-of-top-holders/examples.json
src/strategies/erc20-balance-of-top-holders/index.ts
src/strategies/index.ts

Fixes # .
- Added a strategy, where only first top N token holders can vote

[erc20-balance-of-top-holders] Adding erc20-balance-of-top-holders

---

src/strategies/index.ts
src/strategies/rocketpool-node-operator-v3/README.md
src/strategies/rocketpool-node-operator-v3/examples.json
src/strategies/rocketpool-node-operator-v3/index.ts

An update to the existing rocketpool node operator strategy however using a different formula.

[rocketpool-node-operator-v3] add rocketpool node operator v3 strategy

---

src/strategies/index.ts
src/strategies/sd-vote-boost-twavp-v3/README.md
src/strategies/sd-vote-boost-twavp-v3/examples.json
src/strategies/sd-vote-boost-twavp-v3/index.ts

Fixes # .
- add a new Stake DAO strategy to compute sdTkn voting power

[sd-vote-boost-twavp-v3] Add new strategy

---

src/strategies/aave-governance-power/schema.json

Fixes https://github.com/snapshot-labs/snapshot/issues/4266

Fix type aave-governance-power

---

src/strategies/eoa-balance-and-staking-pools/README.md
src/strategies/eoa-balance-and-staking-pools/examples.json
src/strategies/eoa-balance-and-staking-pools/index.ts
src/strategies/index.ts

Fixes # .
- added strategy eoa-balance-and-staking-pools strategy
- 
-

[eoa-balance-and-staking-pools] added

---

src/strategies/erc20-token-and-single-lp-weighted/README.md
src/strategies/erc20-token-and-single-lp-weighted/examples.json
src/strategies/erc20-token-and-single-lp-weighted/index.ts
src/strategies/erc20-token-and-single-lp-weighted/schema.json
src/strategies/index.ts

Fixes # .
- add erc20-token-and-single-lp-weighted strategy

[erc20-token-and-single-lp-weighted] add erc20-token-and-single-lp-weighted strategy

---

src/strategies/eoa-balance-and-staking-pools/index.ts

Fixes # .
- updated eoa-balance-and-staking-pools strategy
- 
-

[eoa-balance-and-staking-pools] update eoa-balance-and-staking-pools strategy

---

src/strategies/hats-protocol-hat-id/README.md
src/strategies/hats-protocol-hat-id/examples.json
src/strategies/hats-protocol-hat-id/index.ts
src/strategies/hats-protocol-hat-id/schema.json
src/strategies/index.ts

Grants voting power based on if voter has a specific hat (IP based).

[hats-protocol-hat-id] added in hat id strategy

---

src/strategies/vesper/examples.json

Vesper has now a new governance model by the introduction of the `esVSP` token. We're in the transaction phase where both `esVSP` and `VSP` balances will be consider for voting power at `snapshot`.
Refs:
https://docs.vesper.finance/vsp-economics/governance
https://medium.com/vesperfinance/decentralized-governance-5d8b86a8bfe6

[vesper] Update Vesper's voting power contract

---

src/strategies/delegate-registry-v2/examples.json
src/strategies/delegate-registry-v2/index.ts

Adds optional support for "delegate registry v1" delegations in the "delegate registry v2" strategy.

[delegate-registry-v2] Add optional v1 support

---

src/strategies/index.ts
src/strategies/snote/examples.json
src/strategies/snote/index.ts

-  Add a voting strategy for staked NOTE to avoid double counting between delegated sNOTE and undelegated sNOTE.

[snote] add staked-note strategy

---

src/strategies/hats-protocol-hat-ids/index.ts

Fixes hats-protocol-hat-ids strategy.
- Fix hat ID conversion
- Remove subgraph usage

[hats-protocol-hat-ids] Fix hats-protocol-hat-ids strategy

---

src/strategies/delegation-with-cap/README.md
src/strategies/delegation-with-cap/examples.json
src/strategies/delegation-with-cap/index.ts

- Ensure the `delegation-with-cap` strategy caps votes against the total supply, not total cast votes

[delegation-with-cap] fix: delegation-with-cap

---

src/strategies/index.ts
src/strategies/sd-vote-boost-twavp-balanceof/README.md
src/strategies/sd-vote-boost-twavp-balanceof/examples.json
src/strategies/sd-vote-boost-twavp-balanceof/index.ts

[sd-vote-boost-twavp-balanceof] add TWAVP balanceOf for sdCake holders

---

src/strategies/index.ts
src/strategies/sd-vote-boost-twavp-v4/README.md
src/strategies/sd-vote-boost-twavp-v4/examples.json
src/strategies/sd-vote-boost-twavp-v4/index.ts

Fixes # .
Changes proposed in this pull request: new formula voting power

[sd-vote-boost-twavp-v4] twavp-4 new vp formula

---

src/strategies/faraland-staking/examples.json
src/strategies/faraland-staking/index.ts

Fixes # .
- update subgraph URL

[faraland-staking] update subgraph URL

---

src/strategies/balance-of-with-bazaar-batch-auction-linear-vesting-power/examples.json
src/strategies/balance-of-with-bazaar-batch-auction-linear-vesting-power/index.ts
src/strategies/balance-of-with-bazaar-batch-auction-linear-vesting-power/schema.json
src/strategies/index.ts

- Add a new strategy that is ERC20 balance of with bazaar batch auction linear vesting
- This strategy assumes the token is not transferrable for the vesting duration

[balance-of-with-bazaar-batch-auction-linear-vesting-power]: add erc20 balance of with bazaar batch auction linear vesting

---

src/strategies/decentraland-estate-size/index.ts
src/strategies/decentraland-rental-lessors/README.md
src/strategies/decentraland-rental-lessors/examples.json
src/strategies/decentraland-wearable-rarity/index.ts

- Updates Decentraland subgraphs urls

chore: update decentraland urls

---

src/strategies/index.ts
src/strategies/rocketpool-node-operator-v4/README.md
src/strategies/rocketpool-node-operator-v4/examples.json
src/strategies/rocketpool-node-operator-v4/index.ts

With our Houston upgrade, we are changing our Snapshot strategy to reflect our on-chain governance.

[rocketpool-node-operator-v4] Added the rocket-pool-node-operator-v4 strategy

---

src/strategies/index.ts
src/strategies/rocketpool-node-operator-delegate-v5/README.md
src/strategies/rocketpool-node-operator-delegate-v5/examples.json
src/strategies/rocketpool-node-operator-delegate-v5/index.ts

Fixes an issue in the v4 strategy discovered during testing.

[rocketpool-node-operator-delegate-v5] Added the rocket-pool-node-operator-delegate-v5 strategy

---

src/strategies/index.ts
src/strategies/rocketpool-node-operator-delegate-v6/README.md
src/strategies/rocketpool-node-operator-delegate-v6/examples.json
src/strategies/rocketpool-node-operator-delegate-v6/index.ts

Add the rocket-pool-node-operator-delegate-v6 strategy

[rocketpool-node-operator-delegate-v6] Add the rocket-pool-node-operator-delegate-v6 strategy

---

src/strategies/index.ts
src/strategies/swarm-stacking/README.md
src/strategies/swarm-stacking/examples.json
src/strategies/swarm-stacking/index.ts
src/strategies/swarm-stacking/schema.json

Hey there guys,
We have [SMT Stacking platform](https://smt.swarm.com/staking) that stores user tokens inside contracts and not in their wallets obsly. Therefore, we simply wanna make things fair and count these tokens too. I guess it's not the first case you have with stacking, so pls guide me if i missed somewhere

[swarm-stacking] new strategy

---

src/strategies/index.ts
src/strategies/rocketpool-node-operator-v7/README.md
src/strategies/rocketpool-node-operator-v7/examples.json
src/strategies/rocketpool-node-operator-v7/index.ts

New strategy for node operator vote power

[rocketpool-node-operator-v7] Added the rocket-pool-node-operator-v7 strategy

---

src/strategies/index.ts
src/strategies/rocketpool-node-operator-delegate-v7/README.md
src/strategies/rocketpool-node-operator-delegate-v7/examples.json
src/strategies/rocketpool-node-operator-delegate-v7/index.ts

Added the delegate side of the v7 strategy

[rocketpool-node-operator-delegate-v7] Added the rocket-pool-node-operator-delegate-v7 strategy

---

src/strategies/index.ts
src/strategies/moca-staking/README.md
src/strategies/moca-staking/examples.json
src/strategies/moca-staking/index.ts

[moca-staking] add new strategy

---

src/strategies/index.ts
src/strategies/rocketpool-node-operator-delegate-v8/README.md
src/strategies/rocketpool-node-operator-delegate-v8/examples.json
src/strategies/rocketpool-node-operator-delegate-v8/index.ts

Added an updated strategy that fixes an issue with v7.

[rocketpool-node-operator-delegate-v8] Added rocket-pool-node-operator-delegate-v8-strategy

---

src/strategies/frax-finance-fraxtal/examples.json
src/strategies/frax-finance-fraxtal/index.ts
src/strategies/index.ts

Add support for Frax Finance voting on the Fraxtal chain

Frax Finance Fraxtal [frax-finance-fraxtal]

---

src/strategies/index.ts
src/strategies/sd-gauge-less-vote-boost/README.md
src/strategies/sd-gauge-less-vote-boost/examples.json
src/strategies/sd-gauge-less-vote-boost/index.ts

Changes proposed in this pull request: add a new strategy for Stake DAO which calculate the voting power as the working balance

[sd-gauge-less-vote-boost] add strategy with working balance

---

src/strategies/index.ts
src/strategies/superboring/README.md
src/strategies/superboring/examples.json
src/strategies/superboring/index.ts
src/strategies/superboring/schema.json

Adds a strategy for the SuperBoring DCA protocol.
For more information, see https://docs.superboring.xyz

Add strategy for SuperBoring [superboring] 

---

src/strategies/hats-strategy/index.ts

Fixes delegation calculation with hats registry
Note: Voting power coming from vault deposits will not be delegated.

[hats-strategy] Fix delegation of hats-strategy

---

src/strategies/index.ts
src/strategies/sacra-subgraph/README.md
src/strategies/sacra-subgraph/examples.json
src/strategies/sacra-subgraph/index.ts

Fixes # .
- Added new strategy

[sacra-subgraph] add new strategy

---

src/strategies/sacra-subgraph/README.md
src/strategies/sacra-subgraph/index.ts

[sacra-subgraph] Add new power strategy for sacra

---

src/strategies/index.ts
src/strategies/nayms-staking/README.md
src/strategies/nayms-staking/examples.json
src/strategies/nayms-staking/index.ts

Adding a strategy to count NAYM token (deployed on Base) staked by users on the Nayms protocol.

[nayms-staking] nayms staking strategy

---

src/strategies/masterchef-pool-balance-price/README.md
src/strategies/masterchef-pool-balance-price/index.ts

remove redundant words in comment

chore: remove redundant words in comment

---

src/strategies/dappcomposer-getvotingunits/examples.json
src/strategies/dappcomposer-getvotingunits/index.ts
src/strategies/index.ts

Added dAppComposer strategy.
Support for staking tokens using `getVotingUnits` method

[dappcomposer-getvotingunits] strategy addition

---

src/strategies/sablier-v2/configuration.ts

Add new subgraphs for Sablier.

[sablier-v2] refactor: add subgraphs for Sablier

---

src/strategies/erc20-balance-of-saevo/README.md
src/strategies/erc20-balance-of-saevo/examples.json
src/strategies/erc20-balance-of-saevo/index.ts
src/strategies/erc20-balance-of-saevo/schema.json
src/strategies/index.ts

Fixes # .
- Adds staked AEVO strategy, based on amount of AEVO staked on the AEVO staking contract(address) 0x38913051E01D4F6910cB66bB9aC3cb77D746Ad81 on Ethereum Mainnnet
- 
-

[erc20-balance-of-saevo] add saevo strategy

---

src/strategies/index.ts
src/strategies/prl-in-sprl2-balance/README.md
src/strategies/prl-in-sprl2-balance/examples.json
src/strategies/prl-in-sprl2-balance/index.ts

Fixes # .
- Add strategy used for the Parallel.best new tokenomics (sPRL2)
- 
-

[prl-in-sprl2-balance] Feat: add prl-sprl2-balance strategy

---

src/strategies/shroomy-voting-power/schema.json

adress -----> address
Fixes # .
- 
- 
-

fix: typo in `schema.json`
